#![allow(non_snake_case)]
use super::*;
use cudasys::types::cudart::*;

gen_unimplement!("cudaDeviceReset", "cudaError_t");
gen_unimplement!("cudaDeviceSynchronize", "cudaError_t");
gen_unimplement!("cudaDeviceSetLimit", "cudaError_t", "cudaLimit", "size_t");
gen_unimplement!("cudaDeviceGetLimit", "cudaError_t", "*mut size_t", "cudaLimit");
gen_unimplement!("cudaDeviceGetTexture1DLinearMaxWidth", "cudaError_t", "*mut size_t", "*const cudaChannelFormatDesc", "::std::os::raw::c_int");
gen_unimplement!("cudaDeviceGetCacheConfig", "cudaError_t", "*mut cudaFuncCache");
gen_unimplement!("cudaDeviceSetCacheConfig", "cudaError_t", "cudaFuncCache");
gen_unimplement!("cudaDeviceGetSharedMemConfig", "cudaError_t", "*mut cudaSharedMemConfig");
gen_unimplement!("cudaDeviceSetSharedMemConfig", "cudaError_t", "cudaSharedMemConfig");
gen_unimplement!("cudaDeviceGetByPCIBusId", "cudaError_t", "*mut ::std::os::raw::c_int", "*const ::std::os::raw::c_char");
gen_unimplement!("cudaDeviceGetPCIBusId", "cudaError_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cudaIpcGetEventHandle", "cudaError_t", "*mut cudaIpcEventHandle_t", "cudaEvent_t");
gen_unimplement!("cudaIpcOpenEventHandle", "cudaError_t", "*mut cudaEvent_t", "cudaIpcEventHandle_t");
gen_unimplement!("cudaIpcGetMemHandle", "cudaError_t", "*mut cudaIpcMemHandle_t", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaIpcOpenMemHandle", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "cudaIpcMemHandle_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaIpcCloseMemHandle", "cudaError_t", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaDeviceFlushGPUDirectRDMAWrites", "cudaError_t", "cudaFlushGPUDirectRDMAWritesTarget", "cudaFlushGPUDirectRDMAWritesScope");
gen_unimplement!("cudaThreadExit", "cudaError_t");
gen_unimplement!("cudaThreadSynchronize", "cudaError_t");
gen_unimplement!("cudaThreadSetLimit", "cudaError_t", "cudaLimit", "size_t");
gen_unimplement!("cudaThreadGetLimit", "cudaError_t", "*mut size_t", "cudaLimit");
gen_unimplement!("cudaThreadGetCacheConfig", "cudaError_t", "*mut cudaFuncCache");
gen_unimplement!("cudaThreadSetCacheConfig", "cudaError_t", "cudaFuncCache");
gen_unimplement!("cudaGetErrorName", "*const ::std::os::raw::c_char", "cudaError_t");
gen_unimplement!("cudaGetErrorString", "*const ::std::os::raw::c_char", "cudaError_t");
gen_unimplement!("cudaDeviceGetAttribute", "cudaError_t", "*mut ::std::os::raw::c_int", "cudaDeviceAttr", "::std::os::raw::c_int");
gen_unimplement!("cudaDeviceGetDefaultMemPool", "cudaError_t", "*mut cudaMemPool_t", "::std::os::raw::c_int");
gen_unimplement!("cudaDeviceSetMemPool", "cudaError_t", "::std::os::raw::c_int", "cudaMemPool_t");
gen_unimplement!("cudaDeviceGetMemPool", "cudaError_t", "*mut cudaMemPool_t", "::std::os::raw::c_int");
gen_unimplement!("cudaDeviceGetNvSciSyncAttributes", "cudaError_t", "*mut ::std::os::raw::c_void", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cudaDeviceGetP2PAttribute", "cudaError_t", "*mut ::std::os::raw::c_int", "cudaDeviceP2PAttr", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cudaChooseDevice", "cudaError_t", "*mut ::std::os::raw::c_int", "*const cudaDeviceProp");
gen_unimplement!("cudaSetValidDevices", "cudaError_t", "*mut ::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cudaSetDeviceFlags", "cudaError_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaGetDeviceFlags", "cudaError_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("cudaStreamCreate", "cudaError_t", "*mut cudaStream_t");
gen_unimplement!("cudaStreamCreateWithFlags", "cudaError_t", "*mut cudaStream_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaStreamCreateWithPriority", "cudaError_t", "*mut cudaStream_t", "::std::os::raw::c_uint", "::std::os::raw::c_int");
gen_unimplement!("cudaStreamGetPriority", "cudaError_t", "cudaStream_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("cudaStreamGetFlags", "cudaError_t", "cudaStream_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("cudaCtxResetPersistingL2Cache", "cudaError_t");
gen_unimplement!("cudaStreamCopyAttributes", "cudaError_t", "cudaStream_t", "cudaStream_t");
gen_unimplement!("cudaStreamGetAttribute", "cudaError_t", "cudaStream_t", "cudaStreamAttrID", "*mut cudaStreamAttrValue");
gen_unimplement!("cudaStreamSetAttribute", "cudaError_t", "cudaStream_t", "cudaStreamAttrID", "*const cudaStreamAttrValue");
gen_unimplement!("cudaStreamDestroy", "cudaError_t", "cudaStream_t");
gen_unimplement!("cudaStreamWaitEvent", "cudaError_t", "cudaStream_t", "cudaEvent_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaStreamAddCallback", "cudaError_t", "cudaStream_t", "cudaStreamCallback_t", "*mut ::std::os::raw::c_void", "::std::os::raw::c_uint");
gen_unimplement!("cudaStreamQuery", "cudaError_t", "cudaStream_t");
gen_unimplement!("cudaStreamAttachMemAsync", "cudaError_t", "cudaStream_t", "*mut ::std::os::raw::c_void", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaStreamBeginCapture", "cudaError_t", "cudaStream_t", "cudaStreamCaptureMode");
gen_unimplement!("cudaThreadExchangeStreamCaptureMode", "cudaError_t", "*mut cudaStreamCaptureMode");
gen_unimplement!("cudaStreamEndCapture", "cudaError_t", "cudaStream_t", "*mut cudaGraph_t");
gen_unimplement!("cudaStreamGetCaptureInfo", "cudaError_t", "cudaStream_t", "*mut cudaStreamCaptureStatus", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("cudaStreamGetCaptureInfo_v2", "cudaError_t", "cudaStream_t", "*mut cudaStreamCaptureStatus", "*mut ::std::os::raw::c_ulonglong", "*mut cudaGraph_t", "*mut *const cudaGraphNode_t", "*mut size_t");
gen_unimplement!("cudaStreamUpdateCaptureDependencies", "cudaError_t", "cudaStream_t", "*mut cudaGraphNode_t", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaEventCreate", "cudaError_t", "*mut cudaEvent_t");
gen_unimplement!("cudaEventCreateWithFlags", "cudaError_t", "*mut cudaEvent_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaEventRecord", "cudaError_t", "cudaEvent_t", "cudaStream_t");
gen_unimplement!("cudaEventRecordWithFlags", "cudaError_t", "cudaEvent_t", "cudaStream_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaEventQuery", "cudaError_t", "cudaEvent_t");
gen_unimplement!("cudaEventSynchronize", "cudaError_t", "cudaEvent_t");
gen_unimplement!("cudaEventDestroy", "cudaError_t", "cudaEvent_t");
gen_unimplement!("cudaEventElapsedTime", "cudaError_t", "*mut f32", "cudaEvent_t", "cudaEvent_t");
gen_unimplement!("cudaImportExternalMemory", "cudaError_t", "*mut cudaExternalMemory_t", "*const cudaExternalMemoryHandleDesc");
gen_unimplement!("cudaExternalMemoryGetMappedBuffer", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "cudaExternalMemory_t", "*const cudaExternalMemoryBufferDesc");
gen_unimplement!("cudaExternalMemoryGetMappedMipmappedArray", "cudaError_t", "*mut cudaMipmappedArray_t", "cudaExternalMemory_t", "*const cudaExternalMemoryMipmappedArrayDesc");
gen_unimplement!("cudaDestroyExternalMemory", "cudaError_t", "cudaExternalMemory_t");
gen_unimplement!("cudaImportExternalSemaphore", "cudaError_t", "*mut cudaExternalSemaphore_t", "*const cudaExternalSemaphoreHandleDesc");
gen_unimplement!("cudaSignalExternalSemaphoresAsync_v2", "cudaError_t", "*const cudaExternalSemaphore_t", "*const cudaExternalSemaphoreSignalParams", "::std::os::raw::c_uint", "cudaStream_t");
gen_unimplement!("cudaWaitExternalSemaphoresAsync_v2", "cudaError_t", "*const cudaExternalSemaphore_t", "*const cudaExternalSemaphoreWaitParams", "::std::os::raw::c_uint", "cudaStream_t");
gen_unimplement!("cudaDestroyExternalSemaphore", "cudaError_t", "cudaExternalSemaphore_t");
gen_unimplement!("cudaLaunchCooperativeKernel", "cudaError_t", "*const ::std::os::raw::c_void", "dim3", "dim3", "*mut *mut ::std::os::raw::c_void", "size_t", "cudaStream_t");
gen_unimplement!("cudaLaunchCooperativeKernelMultiDevice", "cudaError_t", "*mut cudaLaunchParams", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cudaFuncSetCacheConfig", "cudaError_t", "*const ::std::os::raw::c_void", "cudaFuncCache");
gen_unimplement!("cudaFuncSetSharedMemConfig", "cudaError_t", "*const ::std::os::raw::c_void", "cudaSharedMemConfig");
gen_unimplement!("cudaFuncSetAttribute", "cudaError_t", "*const ::std::os::raw::c_void", "cudaFuncAttribute", "::std::os::raw::c_int");
gen_unimplement!("cudaSetDoubleForDevice", "cudaError_t", "*mut f64");
gen_unimplement!("cudaSetDoubleForHost", "cudaError_t", "*mut f64");
gen_unimplement!("cudaLaunchHostFunc", "cudaError_t", "cudaStream_t", "cudaHostFn_t", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaOccupancyMaxActiveBlocksPerMultiprocessor", "cudaError_t", "*mut ::std::os::raw::c_int", "*const ::std::os::raw::c_void", "::std::os::raw::c_int", "size_t");
gen_unimplement!("cudaOccupancyAvailableDynamicSMemPerBlock", "cudaError_t", "*mut size_t", "*const ::std::os::raw::c_void", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags", "cudaError_t", "*mut ::std::os::raw::c_int", "*const ::std::os::raw::c_void", "::std::os::raw::c_int", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaMallocHost", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "size_t");
gen_unimplement!("cudaMallocPitch", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "*mut size_t", "size_t", "size_t");
gen_unimplement!("cudaMallocArray", "cudaError_t", "*mut cudaArray_t", "*const cudaChannelFormatDesc", "size_t", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaFreeHost", "cudaError_t", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaFreeArray", "cudaError_t", "cudaArray_t");
gen_unimplement!("cudaFreeMipmappedArray", "cudaError_t", "cudaMipmappedArray_t");
gen_unimplement!("cudaHostRegister", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaHostUnregister", "cudaError_t", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaHostGetDevicePointer", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "*mut ::std::os::raw::c_void", "::std::os::raw::c_uint");
gen_unimplement!("cudaHostGetFlags", "cudaError_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaMalloc3D", "cudaError_t", "*mut cudaPitchedPtr", "cudaExtent");
gen_unimplement!("cudaMalloc3DArray", "cudaError_t", "*mut cudaArray_t", "*const cudaChannelFormatDesc", "cudaExtent", "::std::os::raw::c_uint");
gen_unimplement!("cudaMallocMipmappedArray", "cudaError_t", "*mut cudaMipmappedArray_t", "*const cudaChannelFormatDesc", "cudaExtent", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cudaGetMipmappedArrayLevel", "cudaError_t", "*mut cudaArray_t", "cudaMipmappedArray_const_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaMemcpy3D", "cudaError_t", "*const cudaMemcpy3DParms");
gen_unimplement!("cudaMemcpy3DPeer", "cudaError_t", "*const cudaMemcpy3DPeerParms");
gen_unimplement!("cudaMemcpy3DAsync", "cudaError_t", "*const cudaMemcpy3DParms", "cudaStream_t");
gen_unimplement!("cudaMemcpy3DPeerAsync", "cudaError_t", "*const cudaMemcpy3DPeerParms", "cudaStream_t");
gen_unimplement!("cudaArrayGetInfo", "cudaError_t", "*mut cudaChannelFormatDesc", "*mut cudaExtent", "*mut ::std::os::raw::c_uint", "cudaArray_t");
gen_unimplement!("cudaArrayGetPlane", "cudaError_t", "*mut cudaArray_t", "cudaArray_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaArrayGetSparseProperties", "cudaError_t", "*mut cudaArraySparseProperties", "cudaArray_t");
gen_unimplement!("cudaMipmappedArrayGetSparseProperties", "cudaError_t", "*mut cudaArraySparseProperties", "cudaMipmappedArray_t");
gen_unimplement!("cudaMemcpyPeer", "cudaError_t", "*mut ::std::os::raw::c_void", "::std::os::raw::c_int", "*const ::std::os::raw::c_void", "::std::os::raw::c_int", "size_t");
gen_unimplement!("cudaMemcpy2D", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "*const ::std::os::raw::c_void", "size_t", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpy2DToArray", "cudaError_t", "cudaArray_t", "size_t", "size_t", "*const ::std::os::raw::c_void", "size_t", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpy2DFromArray", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "cudaArray_const_t", "size_t", "size_t", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpy2DArrayToArray", "cudaError_t", "cudaArray_t", "size_t", "size_t", "cudaArray_const_t", "size_t", "size_t", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpyToSymbol", "cudaError_t", "*const ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpyFromSymbol", "cudaError_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpyPeerAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "::std::os::raw::c_int", "*const ::std::os::raw::c_void", "::std::os::raw::c_int", "size_t", "cudaStream_t");
gen_unimplement!("cudaMemcpy2DAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "*const ::std::os::raw::c_void", "size_t", "size_t", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMemcpy2DToArrayAsync", "cudaError_t", "cudaArray_t", "size_t", "size_t", "*const ::std::os::raw::c_void", "size_t", "size_t", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMemcpy2DFromArrayAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "cudaArray_const_t", "size_t", "size_t", "size_t", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMemcpyToSymbolAsync", "cudaError_t", "*const ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMemcpyFromSymbolAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMemset", "cudaError_t", "*mut ::std::os::raw::c_void", "::std::os::raw::c_int", "size_t");
gen_unimplement!("cudaMemset2D", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "::std::os::raw::c_int", "size_t", "size_t");
gen_unimplement!("cudaMemset3D", "cudaError_t", "cudaPitchedPtr", "::std::os::raw::c_int", "cudaExtent");
gen_unimplement!("cudaMemsetAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "::std::os::raw::c_int", "size_t", "cudaStream_t");
gen_unimplement!("cudaMemset2DAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "::std::os::raw::c_int", "size_t", "size_t", "cudaStream_t");
gen_unimplement!("cudaMemset3DAsync", "cudaError_t", "cudaPitchedPtr", "::std::os::raw::c_int", "cudaExtent", "cudaStream_t");
gen_unimplement!("cudaGetSymbolAddress", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void");
gen_unimplement!("cudaGetSymbolSize", "cudaError_t", "*mut size_t", "*const ::std::os::raw::c_void");
gen_unimplement!("cudaMemPrefetchAsync", "cudaError_t", "*const ::std::os::raw::c_void", "size_t", "::std::os::raw::c_int", "cudaStream_t");
gen_unimplement!("cudaMemAdvise", "cudaError_t", "*const ::std::os::raw::c_void", "size_t", "cudaMemoryAdvise", "::std::os::raw::c_int");
gen_unimplement!("cudaMemRangeGetAttribute", "cudaError_t", "*mut ::std::os::raw::c_void", "size_t", "cudaMemRangeAttribute", "*const ::std::os::raw::c_void", "size_t");
gen_unimplement!("cudaMemRangeGetAttributes", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "*mut size_t", "*mut cudaMemRangeAttribute", "size_t", "*const ::std::os::raw::c_void", "size_t");
gen_unimplement!("cudaMemcpyToArray", "cudaError_t", "cudaArray_t", "size_t", "size_t", "*const ::std::os::raw::c_void", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpyFromArray", "cudaError_t", "*mut ::std::os::raw::c_void", "cudaArray_const_t", "size_t", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpyArrayToArray", "cudaError_t", "cudaArray_t", "size_t", "size_t", "cudaArray_const_t", "size_t", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaMemcpyToArrayAsync", "cudaError_t", "cudaArray_t", "size_t", "size_t", "*const ::std::os::raw::c_void", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMemcpyFromArrayAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "cudaArray_const_t", "size_t", "size_t", "size_t", "cudaMemcpyKind", "cudaStream_t");
gen_unimplement!("cudaMallocAsync", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "size_t", "cudaStream_t");
gen_unimplement!("cudaFreeAsync", "cudaError_t", "*mut ::std::os::raw::c_void", "cudaStream_t");
gen_unimplement!("cudaMemPoolTrimTo", "cudaError_t", "cudaMemPool_t", "size_t");
gen_unimplement!("cudaMemPoolSetAttribute", "cudaError_t", "cudaMemPool_t", "cudaMemPoolAttr", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaMemPoolGetAttribute", "cudaError_t", "cudaMemPool_t", "cudaMemPoolAttr", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaMemPoolSetAccess", "cudaError_t", "cudaMemPool_t", "*const cudaMemAccessDesc", "size_t");
gen_unimplement!("cudaMemPoolGetAccess", "cudaError_t", "*mut cudaMemAccessFlags", "cudaMemPool_t", "*mut cudaMemLocation");
gen_unimplement!("cudaMemPoolCreate", "cudaError_t", "*mut cudaMemPool_t", "*const cudaMemPoolProps");
gen_unimplement!("cudaMemPoolDestroy", "cudaError_t", "cudaMemPool_t");
gen_unimplement!("cudaMallocFromPoolAsync", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "size_t", "cudaMemPool_t", "cudaStream_t");
gen_unimplement!("cudaMemPoolExportToShareableHandle", "cudaError_t", "*mut ::std::os::raw::c_void", "cudaMemPool_t", "cudaMemAllocationHandleType", "::std::os::raw::c_uint");
gen_unimplement!("cudaMemPoolImportFromShareableHandle", "cudaError_t", "*mut cudaMemPool_t", "*mut ::std::os::raw::c_void", "cudaMemAllocationHandleType", "::std::os::raw::c_uint");
gen_unimplement!("cudaMemPoolExportPointer", "cudaError_t", "*mut cudaMemPoolPtrExportData", "*mut ::std::os::raw::c_void");
gen_unimplement!("cudaMemPoolImportPointer", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "cudaMemPool_t", "*mut cudaMemPoolPtrExportData");
gen_unimplement!("cudaDeviceCanAccessPeer", "cudaError_t", "*mut ::std::os::raw::c_int", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cudaDeviceEnablePeerAccess", "cudaError_t", "::std::os::raw::c_int", "::std::os::raw::c_uint");
gen_unimplement!("cudaDeviceDisablePeerAccess", "cudaError_t", "::std::os::raw::c_int");
gen_unimplement!("cudaGraphicsUnregisterResource", "cudaError_t", "cudaGraphicsResource_t");
gen_unimplement!("cudaGraphicsResourceSetMapFlags", "cudaError_t", "cudaGraphicsResource_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaGraphicsMapResources", "cudaError_t", "::std::os::raw::c_int", "*mut cudaGraphicsResource_t", "cudaStream_t");
gen_unimplement!("cudaGraphicsUnmapResources", "cudaError_t", "::std::os::raw::c_int", "*mut cudaGraphicsResource_t", "cudaStream_t");
gen_unimplement!("cudaGraphicsResourceGetMappedPointer", "cudaError_t", "*mut *mut ::std::os::raw::c_void", "*mut size_t", "cudaGraphicsResource_t");
gen_unimplement!("cudaGraphicsSubResourceGetMappedArray", "cudaError_t", "*mut cudaArray_t", "cudaGraphicsResource_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cudaGraphicsResourceGetMappedMipmappedArray", "cudaError_t", "*mut cudaMipmappedArray_t", "cudaGraphicsResource_t");
gen_unimplement!("cudaBindTexture", "cudaError_t", "*mut size_t", "*const textureReference", "*const ::std::os::raw::c_void", "*const cudaChannelFormatDesc", "size_t");
gen_unimplement!("cudaBindTexture2D", "cudaError_t", "*mut size_t", "*const textureReference", "*const ::std::os::raw::c_void", "*const cudaChannelFormatDesc", "size_t", "size_t", "size_t");
gen_unimplement!("cudaBindTextureToArray", "cudaError_t", "*const textureReference", "cudaArray_const_t", "*const cudaChannelFormatDesc");
gen_unimplement!("cudaBindTextureToMipmappedArray", "cudaError_t", "*const textureReference", "cudaMipmappedArray_const_t", "*const cudaChannelFormatDesc");
gen_unimplement!("cudaUnbindTexture", "cudaError_t", "*const textureReference");
gen_unimplement!("cudaGetTextureAlignmentOffset", "cudaError_t", "*mut size_t", "*const textureReference");
gen_unimplement!("cudaGetTextureReference", "cudaError_t", "*mut *const textureReference", "*const ::std::os::raw::c_void");
gen_unimplement!("cudaBindSurfaceToArray", "cudaError_t", "*const surfaceReference", "cudaArray_const_t", "*const cudaChannelFormatDesc");
gen_unimplement!("cudaGetSurfaceReference", "cudaError_t", "*mut *const surfaceReference", "*const ::std::os::raw::c_void");
gen_unimplement!("cudaGetChannelDesc", "cudaError_t", "*mut cudaChannelFormatDesc", "cudaArray_const_t");
gen_unimplement!("cudaCreateChannelDesc", "cudaChannelFormatDesc", "::std::os::raw::c_int", "::std::os::raw::c_int", "::std::os::raw::c_int", "::std::os::raw::c_int", "cudaChannelFormatKind");
gen_unimplement!("cudaCreateTextureObject", "cudaError_t", "*mut cudaTextureObject_t", "*const cudaResourceDesc", "*const cudaTextureDesc", "*const cudaResourceViewDesc");
gen_unimplement!("cudaDestroyTextureObject", "cudaError_t", "cudaTextureObject_t");
gen_unimplement!("cudaGetTextureObjectResourceDesc", "cudaError_t", "*mut cudaResourceDesc", "cudaTextureObject_t");
gen_unimplement!("cudaGetTextureObjectTextureDesc", "cudaError_t", "*mut cudaTextureDesc", "cudaTextureObject_t");
gen_unimplement!("cudaGetTextureObjectResourceViewDesc", "cudaError_t", "*mut cudaResourceViewDesc", "cudaTextureObject_t");
gen_unimplement!("cudaCreateSurfaceObject", "cudaError_t", "*mut cudaSurfaceObject_t", "*const cudaResourceDesc");
gen_unimplement!("cudaDestroySurfaceObject", "cudaError_t", "cudaSurfaceObject_t");
gen_unimplement!("cudaGetSurfaceObjectResourceDesc", "cudaError_t", "*mut cudaResourceDesc", "cudaSurfaceObject_t");
gen_unimplement!("cudaDriverGetVersion", "cudaError_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("cudaRuntimeGetVersion", "cudaError_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("cudaGraphCreate", "cudaError_t", "*mut cudaGraph_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaGraphAddKernelNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const cudaKernelNodeParams");
gen_unimplement!("cudaGraphKernelNodeGetParams", "cudaError_t", "cudaGraphNode_t", "*mut cudaKernelNodeParams");
gen_unimplement!("cudaGraphKernelNodeSetParams", "cudaError_t", "cudaGraphNode_t", "*const cudaKernelNodeParams");
gen_unimplement!("cudaGraphKernelNodeCopyAttributes", "cudaError_t", "cudaGraphNode_t", "cudaGraphNode_t");
gen_unimplement!("cudaGraphKernelNodeGetAttribute", "cudaError_t", "cudaGraphNode_t", "cudaKernelNodeAttrID", "*mut cudaKernelNodeAttrValue");
gen_unimplement!("cudaGraphKernelNodeSetAttribute", "cudaError_t", "cudaGraphNode_t", "cudaKernelNodeAttrID", "*const cudaKernelNodeAttrValue");
gen_unimplement!("cudaGraphAddMemcpyNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const cudaMemcpy3DParms");
gen_unimplement!("cudaGraphAddMemcpyNodeToSymbol", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphAddMemcpyNodeFromSymbol", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphAddMemcpyNode1D", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphMemcpyNodeGetParams", "cudaError_t", "cudaGraphNode_t", "*mut cudaMemcpy3DParms");
gen_unimplement!("cudaGraphMemcpyNodeSetParams", "cudaError_t", "cudaGraphNode_t", "*const cudaMemcpy3DParms");
gen_unimplement!("cudaGraphMemcpyNodeSetParamsToSymbol", "cudaError_t", "cudaGraphNode_t", "*const ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphMemcpyNodeSetParamsFromSymbol", "cudaError_t", "cudaGraphNode_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphMemcpyNodeSetParams1D", "cudaError_t", "cudaGraphNode_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphAddMemsetNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const cudaMemsetParams");
gen_unimplement!("cudaGraphMemsetNodeGetParams", "cudaError_t", "cudaGraphNode_t", "*mut cudaMemsetParams");
gen_unimplement!("cudaGraphMemsetNodeSetParams", "cudaError_t", "cudaGraphNode_t", "*const cudaMemsetParams");
gen_unimplement!("cudaGraphAddHostNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const cudaHostNodeParams");
gen_unimplement!("cudaGraphHostNodeGetParams", "cudaError_t", "cudaGraphNode_t", "*mut cudaHostNodeParams");
gen_unimplement!("cudaGraphHostNodeSetParams", "cudaError_t", "cudaGraphNode_t", "*const cudaHostNodeParams");
gen_unimplement!("cudaGraphAddChildGraphNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "cudaGraph_t");
gen_unimplement!("cudaGraphChildGraphNodeGetGraph", "cudaError_t", "cudaGraphNode_t", "*mut cudaGraph_t");
gen_unimplement!("cudaGraphAddEmptyNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t");
gen_unimplement!("cudaGraphAddEventRecordNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "cudaEvent_t");
gen_unimplement!("cudaGraphEventRecordNodeGetEvent", "cudaError_t", "cudaGraphNode_t", "*mut cudaEvent_t");
gen_unimplement!("cudaGraphEventRecordNodeSetEvent", "cudaError_t", "cudaGraphNode_t", "cudaEvent_t");
gen_unimplement!("cudaGraphAddEventWaitNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "cudaEvent_t");
gen_unimplement!("cudaGraphEventWaitNodeGetEvent", "cudaError_t", "cudaGraphNode_t", "*mut cudaEvent_t");
gen_unimplement!("cudaGraphEventWaitNodeSetEvent", "cudaError_t", "cudaGraphNode_t", "cudaEvent_t");
gen_unimplement!("cudaGraphAddExternalSemaphoresSignalNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const cudaExternalSemaphoreSignalNodeParams");
gen_unimplement!("cudaGraphExternalSemaphoresSignalNodeGetParams", "cudaError_t", "cudaGraphNode_t", "*mut cudaExternalSemaphoreSignalNodeParams");
gen_unimplement!("cudaGraphExternalSemaphoresSignalNodeSetParams", "cudaError_t", "cudaGraphNode_t", "*const cudaExternalSemaphoreSignalNodeParams");
gen_unimplement!("cudaGraphAddExternalSemaphoresWaitNode", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraph_t", "*const cudaGraphNode_t", "size_t", "*const cudaExternalSemaphoreWaitNodeParams");
gen_unimplement!("cudaGraphExternalSemaphoresWaitNodeGetParams", "cudaError_t", "cudaGraphNode_t", "*mut cudaExternalSemaphoreWaitNodeParams");
gen_unimplement!("cudaGraphExternalSemaphoresWaitNodeSetParams", "cudaError_t", "cudaGraphNode_t", "*const cudaExternalSemaphoreWaitNodeParams");
gen_unimplement!("cudaGraphClone", "cudaError_t", "*mut cudaGraph_t", "cudaGraph_t");
gen_unimplement!("cudaGraphNodeFindInClone", "cudaError_t", "*mut cudaGraphNode_t", "cudaGraphNode_t", "cudaGraph_t");
gen_unimplement!("cudaGraphNodeGetType", "cudaError_t", "cudaGraphNode_t", "*mut cudaGraphNodeType");
gen_unimplement!("cudaGraphGetNodes", "cudaError_t", "cudaGraph_t", "*mut cudaGraphNode_t", "*mut size_t");
gen_unimplement!("cudaGraphGetRootNodes", "cudaError_t", "cudaGraph_t", "*mut cudaGraphNode_t", "*mut size_t");
gen_unimplement!("cudaGraphGetEdges", "cudaError_t", "cudaGraph_t", "*mut cudaGraphNode_t", "*mut cudaGraphNode_t", "*mut size_t");
gen_unimplement!("cudaGraphNodeGetDependencies", "cudaError_t", "cudaGraphNode_t", "*mut cudaGraphNode_t", "*mut size_t");
gen_unimplement!("cudaGraphNodeGetDependentNodes", "cudaError_t", "cudaGraphNode_t", "*mut cudaGraphNode_t", "*mut size_t");
gen_unimplement!("cudaGraphAddDependencies", "cudaError_t", "cudaGraph_t", "*const cudaGraphNode_t", "*const cudaGraphNode_t", "size_t");
gen_unimplement!("cudaGraphRemoveDependencies", "cudaError_t", "cudaGraph_t", "*const cudaGraphNode_t", "*const cudaGraphNode_t", "size_t");
gen_unimplement!("cudaGraphDestroyNode", "cudaError_t", "cudaGraphNode_t");
gen_unimplement!("cudaGraphInstantiate", "cudaError_t", "*mut cudaGraphExec_t", "cudaGraph_t", "*mut cudaGraphNode_t", "*mut ::std::os::raw::c_char", "size_t");
gen_unimplement!("cudaGraphExecKernelNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const cudaKernelNodeParams");
gen_unimplement!("cudaGraphExecMemcpyNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const cudaMemcpy3DParms");
gen_unimplement!("cudaGraphExecMemcpyNodeSetParamsToSymbol", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphExecMemcpyNodeSetParamsFromSymbol", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphExecMemcpyNodeSetParams1D", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*mut ::std::os::raw::c_void", "*const ::std::os::raw::c_void", "size_t", "cudaMemcpyKind");
gen_unimplement!("cudaGraphExecMemsetNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const cudaMemsetParams");
gen_unimplement!("cudaGraphExecHostNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const cudaHostNodeParams");
gen_unimplement!("cudaGraphExecChildGraphNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "cudaGraph_t");
gen_unimplement!("cudaGraphExecEventRecordNodeSetEvent", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "cudaEvent_t");
gen_unimplement!("cudaGraphExecEventWaitNodeSetEvent", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "cudaEvent_t");
gen_unimplement!("cudaGraphExecExternalSemaphoresSignalNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const cudaExternalSemaphoreSignalNodeParams");
gen_unimplement!("cudaGraphExecExternalSemaphoresWaitNodeSetParams", "cudaError_t", "cudaGraphExec_t", "cudaGraphNode_t", "*const cudaExternalSemaphoreWaitNodeParams");
gen_unimplement!("cudaGraphExecUpdate", "cudaError_t", "cudaGraphExec_t", "cudaGraph_t", "*mut cudaGraphNode_t", "*mut cudaGraphExecUpdateResult");
gen_unimplement!("cudaGraphUpload", "cudaError_t", "cudaGraphExec_t", "cudaStream_t");
gen_unimplement!("cudaGraphLaunch", "cudaError_t", "cudaGraphExec_t", "cudaStream_t");
gen_unimplement!("cudaGraphExecDestroy", "cudaError_t", "cudaGraphExec_t");
gen_unimplement!("cudaGraphDestroy", "cudaError_t", "cudaGraph_t");
gen_unimplement!("cudaGraphDebugDotPrint", "cudaError_t", "cudaGraph_t", "*const ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("cudaUserObjectCreate", "cudaError_t", "*mut cudaUserObject_t", "*mut ::std::os::raw::c_void", "cudaHostFn_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cudaUserObjectRetain", "cudaError_t", "cudaUserObject_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaUserObjectRelease", "cudaError_t", "cudaUserObject_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaGraphRetainUserObject", "cudaError_t", "cudaGraph_t", "cudaUserObject_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cudaGraphReleaseUserObject", "cudaError_t", "cudaGraph_t", "cudaUserObject_t", "::std::os::raw::c_uint");
gen_unimplement!("cudaGetDriverEntryPoint", "cudaError_t", "*const ::std::os::raw::c_char", "*mut *mut ::std::os::raw::c_void", "::std::os::raw::c_ulonglong");
gen_unimplement!("cudaGetExportTable", "cudaError_t", "*mut *const ::std::os::raw::c_void", "*const cudaUUID_t");
gen_unimplement!("cudaGetFuncBySymbol", "cudaError_t", "*mut cudaFunction_t", "*const ::std::os::raw::c_void");
