#![allow(non_snake_case)]
use super::*;
use cudasys::types::cuda::*;

gen_unimplement!("cuGetErrorString", "CUresult", "CUresult", "*mut *const ::std::os::raw::c_char");
gen_unimplement!("cuGetErrorName", "CUresult", "CUresult", "*mut *const ::std::os::raw::c_char");
gen_unimplement!("cuInit", "CUresult", "::std::os::raw::c_uint");
gen_unimplement!("cuDriverGetVersion", "CUresult", "*mut ::std::os::raw::c_int");
gen_unimplement!("cuDeviceGet", "CUresult", "*mut CUdevice", "::std::os::raw::c_int");
gen_unimplement!("cuDeviceGetCount", "CUresult", "*mut ::std::os::raw::c_int");
gen_unimplement!("cuDeviceGetName", "CUresult", "*mut ::std::os::raw::c_char", "::std::os::raw::c_int", "CUdevice");
gen_unimplement!("cuDeviceGetUuid", "CUresult", "*mut CUuuid", "CUdevice");
gen_unimplement!("cuDeviceGetLuid", "CUresult", "*mut ::std::os::raw::c_char", "*mut ::std::os::raw::c_uint", "CUdevice");
gen_unimplement!("cuDeviceTotalMem_v2", "CUresult", "*mut size_t", "CUdevice");
gen_unimplement!("cuDeviceGetTexture1DLinearMaxWidth", "CUresult", "*mut size_t", "CUarray_format", "::std::os::raw::c_uint", "CUdevice");
gen_unimplement!("cuDeviceGetAttribute", "CUresult", "*mut ::std::os::raw::c_int", "CUdevice_attribute", "CUdevice");
gen_unimplement!("cuDeviceGetNvSciSyncAttributes", "CUresult", "*mut ::std::os::raw::c_void", "CUdevice", "::std::os::raw::c_int");
gen_unimplement!("cuDeviceSetMemPool", "CUresult", "CUdevice", "CUmemoryPool");
gen_unimplement!("cuDeviceGetMemPool", "CUresult", "*mut CUmemoryPool", "CUdevice");
gen_unimplement!("cuDeviceGetDefaultMemPool", "CUresult", "*mut CUmemoryPool", "CUdevice");
gen_unimplement!("cuDeviceGetProperties", "CUresult", "*mut CUdevprop", "CUdevice");
gen_unimplement!("cuDeviceComputeCapability", "CUresult", "*mut ::std::os::raw::c_int", "*mut ::std::os::raw::c_int", "CUdevice");
gen_unimplement!("cuDevicePrimaryCtxRetain", "CUresult", "*mut CUcontext", "CUdevice");
gen_unimplement!("cuDevicePrimaryCtxRelease_v2", "CUresult", "CUdevice");
gen_unimplement!("cuDevicePrimaryCtxSetFlags_v2", "CUresult", "CUdevice", "::std::os::raw::c_uint");
gen_unimplement!("cuDevicePrimaryCtxReset_v2", "CUresult", "CUdevice");
gen_unimplement!("cuCtxCreate_v2", "CUresult", "*mut CUcontext", "::std::os::raw::c_uint", "CUdevice");
gen_unimplement!("cuCtxDestroy_v2", "CUresult", "CUcontext");
gen_unimplement!("cuCtxPushCurrent_v2", "CUresult", "CUcontext");
gen_unimplement!("cuCtxPopCurrent_v2", "CUresult", "*mut CUcontext");
gen_unimplement!("cuCtxSetCurrent", "CUresult", "CUcontext");
gen_unimplement!("cuCtxGetCurrent", "CUresult", "*mut CUcontext");
gen_unimplement!("cuCtxGetDevice", "CUresult", "*mut CUdevice");
gen_unimplement!("cuCtxGetFlags", "CUresult", "*mut ::std::os::raw::c_uint");
gen_unimplement!("cuCtxSynchronize", "CUresult");
gen_unimplement!("cuCtxSetLimit", "CUresult", "CUlimit", "size_t");
gen_unimplement!("cuCtxGetLimit", "CUresult", "*mut size_t", "CUlimit");
gen_unimplement!("cuCtxGetCacheConfig", "CUresult", "*mut CUfunc_cache");
gen_unimplement!("cuCtxSetCacheConfig", "CUresult", "CUfunc_cache");
gen_unimplement!("cuCtxGetSharedMemConfig", "CUresult", "*mut CUsharedconfig");
gen_unimplement!("cuCtxSetSharedMemConfig", "CUresult", "CUsharedconfig");
gen_unimplement!("cuCtxGetApiVersion", "CUresult", "CUcontext", "*mut ::std::os::raw::c_uint");
gen_unimplement!("cuCtxGetStreamPriorityRange", "CUresult", "*mut ::std::os::raw::c_int", "*mut ::std::os::raw::c_int");
gen_unimplement!("cuCtxResetPersistingL2Cache", "CUresult");
gen_unimplement!("cuCtxAttach", "CUresult", "*mut CUcontext", "::std::os::raw::c_uint");
gen_unimplement!("cuCtxDetach", "CUresult", "CUcontext");
gen_unimplement!("cuModuleLoad", "CUresult", "*mut CUmodule", "*const ::std::os::raw::c_char");
gen_unimplement!("cuModuleLoadData", "CUresult", "*mut CUmodule", "*const ::std::os::raw::c_void");
gen_unimplement!("cuModuleLoadDataEx", "CUresult", "*mut CUmodule", "*const ::std::os::raw::c_void", "::std::os::raw::c_uint", "*mut CUjit_option", "*mut *mut ::std::os::raw::c_void");
gen_unimplement!("cuModuleLoadFatBinary", "CUresult", "*mut CUmodule", "*const ::std::os::raw::c_void");
gen_unimplement!("cuModuleUnload", "CUresult", "CUmodule");
gen_unimplement!("cuModuleGetFunction", "CUresult", "*mut CUfunction", "CUmodule", "*const ::std::os::raw::c_char");
gen_unimplement!("cuModuleGetGlobal_v2", "CUresult", "*mut CUdeviceptr", "*mut size_t", "CUmodule", "*const ::std::os::raw::c_char");
gen_unimplement!("cuModuleGetTexRef", "CUresult", "*mut CUtexref", "CUmodule", "*const ::std::os::raw::c_char");
gen_unimplement!("cuModuleGetSurfRef", "CUresult", "*mut CUsurfref", "CUmodule", "*const ::std::os::raw::c_char");
gen_unimplement!("cuLinkCreate_v2", "CUresult", "::std::os::raw::c_uint", "*mut CUjit_option", "*mut *mut ::std::os::raw::c_void", "*mut CUlinkState");
gen_unimplement!("cuLinkAddData_v2", "CUresult", "CUlinkState", "CUjitInputType", "*mut ::std::os::raw::c_void", "size_t", "*const ::std::os::raw::c_char", "::std::os::raw::c_uint", "*mut CUjit_option", "*mut *mut ::std::os::raw::c_void");
gen_unimplement!("cuLinkAddFile_v2", "CUresult", "CUlinkState", "CUjitInputType", "*const ::std::os::raw::c_char", "::std::os::raw::c_uint", "*mut CUjit_option", "*mut *mut ::std::os::raw::c_void");
gen_unimplement!("cuLinkComplete", "CUresult", "CUlinkState", "*mut *mut ::std::os::raw::c_void", "*mut size_t");
gen_unimplement!("cuLinkDestroy", "CUresult", "CUlinkState");
gen_unimplement!("cuMemGetInfo_v2", "CUresult", "*mut size_t", "*mut size_t");
gen_unimplement!("cuMemAlloc_v2", "CUresult", "*mut CUdeviceptr", "size_t");
gen_unimplement!("cuMemAllocPitch_v2", "CUresult", "*mut CUdeviceptr", "*mut size_t", "size_t", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuMemFree_v2", "CUresult", "CUdeviceptr");
gen_unimplement!("cuMemGetAddressRange_v2", "CUresult", "*mut CUdeviceptr", "*mut size_t", "CUdeviceptr");
gen_unimplement!("cuMemAllocHost_v2", "CUresult", "*mut *mut ::std::os::raw::c_void", "size_t");
gen_unimplement!("cuMemFreeHost", "CUresult", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuMemHostAlloc", "CUresult", "*mut *mut ::std::os::raw::c_void", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuMemHostGetDevicePointer_v2", "CUresult", "*mut CUdeviceptr", "*mut ::std::os::raw::c_void", "::std::os::raw::c_uint");
gen_unimplement!("cuMemHostGetFlags", "CUresult", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuMemAllocManaged", "CUresult", "*mut CUdeviceptr", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuDeviceGetByPCIBusId", "CUresult", "*mut CUdevice", "*const ::std::os::raw::c_char");
gen_unimplement!("cuDeviceGetPCIBusId", "CUresult", "*mut ::std::os::raw::c_char", "::std::os::raw::c_int", "CUdevice");
gen_unimplement!("cuIpcGetEventHandle", "CUresult", "*mut CUipcEventHandle", "CUevent");
gen_unimplement!("cuIpcOpenEventHandle", "CUresult", "*mut CUevent", "CUipcEventHandle");
gen_unimplement!("cuIpcGetMemHandle", "CUresult", "*mut CUipcMemHandle", "CUdeviceptr");
gen_unimplement!("cuIpcOpenMemHandle_v2", "CUresult", "*mut CUdeviceptr", "CUipcMemHandle", "::std::os::raw::c_uint");
gen_unimplement!("cuIpcCloseMemHandle", "CUresult", "CUdeviceptr");
gen_unimplement!("cuMemHostRegister_v2", "CUresult", "*mut ::std::os::raw::c_void", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuMemHostUnregister", "CUresult", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuMemcpy", "CUresult", "CUdeviceptr", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemcpyPeer", "CUresult", "CUdeviceptr", "CUcontext", "CUdeviceptr", "CUcontext", "size_t");
gen_unimplement!("cuMemcpyHtoD_v2", "CUresult", "CUdeviceptr", "*const ::std::os::raw::c_void", "size_t");
gen_unimplement!("cuMemcpyDtoH_v2", "CUresult", "*mut ::std::os::raw::c_void", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemcpyDtoD_v2", "CUresult", "CUdeviceptr", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemcpyDtoA_v2", "CUresult", "CUarray", "size_t", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemcpyAtoD_v2", "CUresult", "CUdeviceptr", "CUarray", "size_t", "size_t");
gen_unimplement!("cuMemcpyHtoA_v2", "CUresult", "CUarray", "size_t", "*const ::std::os::raw::c_void", "size_t");
gen_unimplement!("cuMemcpyAtoH_v2", "CUresult", "*mut ::std::os::raw::c_void", "CUarray", "size_t", "size_t");
gen_unimplement!("cuMemcpyAtoA_v2", "CUresult", "CUarray", "size_t", "CUarray", "size_t", "size_t");
gen_unimplement!("cuMemcpy2D_v2", "CUresult", "*const CUDA_MEMCPY2D");
gen_unimplement!("cuMemcpy2DUnaligned_v2", "CUresult", "*const CUDA_MEMCPY2D");
gen_unimplement!("cuMemcpy3D_v2", "CUresult", "*const CUDA_MEMCPY3D");
gen_unimplement!("cuMemcpy3DPeer", "CUresult", "*const CUDA_MEMCPY3D_PEER");
gen_unimplement!("cuMemcpyAsync", "CUresult", "CUdeviceptr", "CUdeviceptr", "size_t", "CUstream");
gen_unimplement!("cuMemcpyPeerAsync", "CUresult", "CUdeviceptr", "CUcontext", "CUdeviceptr", "CUcontext", "size_t", "CUstream");
gen_unimplement!("cuMemcpyHtoDAsync_v2", "CUresult", "CUdeviceptr", "*const ::std::os::raw::c_void", "size_t", "CUstream");
gen_unimplement!("cuMemcpyDtoHAsync_v2", "CUresult", "*mut ::std::os::raw::c_void", "CUdeviceptr", "size_t", "CUstream");
gen_unimplement!("cuMemcpyDtoDAsync_v2", "CUresult", "CUdeviceptr", "CUdeviceptr", "size_t", "CUstream");
gen_unimplement!("cuMemcpyHtoAAsync_v2", "CUresult", "CUarray", "size_t", "*const ::std::os::raw::c_void", "size_t", "CUstream");
gen_unimplement!("cuMemcpyAtoHAsync_v2", "CUresult", "*mut ::std::os::raw::c_void", "CUarray", "size_t", "size_t", "CUstream");
gen_unimplement!("cuMemcpy2DAsync_v2", "CUresult", "*const CUDA_MEMCPY2D", "CUstream");
gen_unimplement!("cuMemcpy3DAsync_v2", "CUresult", "*const CUDA_MEMCPY3D", "CUstream");
gen_unimplement!("cuMemcpy3DPeerAsync", "CUresult", "*const CUDA_MEMCPY3D_PEER", "CUstream");
gen_unimplement!("cuMemsetD8_v2", "CUresult", "CUdeviceptr", "::std::os::raw::c_uchar", "size_t");
gen_unimplement!("cuMemsetD16_v2", "CUresult", "CUdeviceptr", "::std::os::raw::c_ushort", "size_t");
gen_unimplement!("cuMemsetD32_v2", "CUresult", "CUdeviceptr", "::std::os::raw::c_uint", "size_t");
gen_unimplement!("cuMemsetD2D8_v2", "CUresult", "CUdeviceptr", "size_t", "::std::os::raw::c_uchar", "size_t", "size_t");
gen_unimplement!("cuMemsetD2D16_v2", "CUresult", "CUdeviceptr", "size_t", "::std::os::raw::c_ushort", "size_t", "size_t");
gen_unimplement!("cuMemsetD2D32_v2", "CUresult", "CUdeviceptr", "size_t", "::std::os::raw::c_uint", "size_t", "size_t");
gen_unimplement!("cuMemsetD8Async", "CUresult", "CUdeviceptr", "::std::os::raw::c_uchar", "size_t", "CUstream");
gen_unimplement!("cuMemsetD16Async", "CUresult", "CUdeviceptr", "::std::os::raw::c_ushort", "size_t", "CUstream");
gen_unimplement!("cuMemsetD32Async", "CUresult", "CUdeviceptr", "::std::os::raw::c_uint", "size_t", "CUstream");
gen_unimplement!("cuMemsetD2D8Async", "CUresult", "CUdeviceptr", "size_t", "::std::os::raw::c_uchar", "size_t", "size_t", "CUstream");
gen_unimplement!("cuMemsetD2D16Async", "CUresult", "CUdeviceptr", "size_t", "::std::os::raw::c_ushort", "size_t", "size_t", "CUstream");
gen_unimplement!("cuMemsetD2D32Async", "CUresult", "CUdeviceptr", "size_t", "::std::os::raw::c_uint", "size_t", "size_t", "CUstream");
gen_unimplement!("cuArrayCreate_v2", "CUresult", "*mut CUarray", "*const CUDA_ARRAY_DESCRIPTOR");
gen_unimplement!("cuArrayGetDescriptor_v2", "CUresult", "*mut CUDA_ARRAY_DESCRIPTOR", "CUarray");
gen_unimplement!("cuArrayGetSparseProperties", "CUresult", "*mut CUDA_ARRAY_SPARSE_PROPERTIES", "CUarray");
gen_unimplement!("cuMipmappedArrayGetSparseProperties", "CUresult", "*mut CUDA_ARRAY_SPARSE_PROPERTIES", "CUmipmappedArray");
gen_unimplement!("cuArrayGetPlane", "CUresult", "*mut CUarray", "CUarray", "::std::os::raw::c_uint");
gen_unimplement!("cuArrayDestroy", "CUresult", "CUarray");
gen_unimplement!("cuArray3DCreate_v2", "CUresult", "*mut CUarray", "*const CUDA_ARRAY3D_DESCRIPTOR");
gen_unimplement!("cuArray3DGetDescriptor_v2", "CUresult", "*mut CUDA_ARRAY3D_DESCRIPTOR", "CUarray");
gen_unimplement!("cuMipmappedArrayCreate", "CUresult", "*mut CUmipmappedArray", "*const CUDA_ARRAY3D_DESCRIPTOR", "::std::os::raw::c_uint");
gen_unimplement!("cuMipmappedArrayGetLevel", "CUresult", "*mut CUarray", "CUmipmappedArray", "::std::os::raw::c_uint");
gen_unimplement!("cuMipmappedArrayDestroy", "CUresult", "CUmipmappedArray");
gen_unimplement!("cuMemAddressReserve", "CUresult", "*mut CUdeviceptr", "size_t", "size_t", "CUdeviceptr", "::std::os::raw::c_ulonglong");
gen_unimplement!("cuMemAddressFree", "CUresult", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemCreate", "CUresult", "*mut CUmemGenericAllocationHandle", "size_t", "*const CUmemAllocationProp", "::std::os::raw::c_ulonglong");
gen_unimplement!("cuMemRelease", "CUresult", "CUmemGenericAllocationHandle");
gen_unimplement!("cuMemMap", "CUresult", "CUdeviceptr", "size_t", "size_t", "CUmemGenericAllocationHandle", "::std::os::raw::c_ulonglong");
gen_unimplement!("cuMemMapArrayAsync", "CUresult", "*mut CUarrayMapInfo", "::std::os::raw::c_uint", "CUstream");
gen_unimplement!("cuMemUnmap", "CUresult", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemSetAccess", "CUresult", "CUdeviceptr", "size_t", "*const CUmemAccessDesc", "size_t");
gen_unimplement!("cuMemGetAccess", "CUresult", "*mut ::std::os::raw::c_ulonglong", "*const CUmemLocation", "CUdeviceptr");
gen_unimplement!("cuMemExportToShareableHandle", "CUresult", "*mut ::std::os::raw::c_void", "CUmemGenericAllocationHandle", "CUmemAllocationHandleType", "::std::os::raw::c_ulonglong");
gen_unimplement!("cuMemImportFromShareableHandle", "CUresult", "*mut CUmemGenericAllocationHandle", "*mut ::std::os::raw::c_void", "CUmemAllocationHandleType");
gen_unimplement!("cuMemGetAllocationGranularity", "CUresult", "*mut size_t", "*const CUmemAllocationProp", "CUmemAllocationGranularity_flags");
gen_unimplement!("cuMemGetAllocationPropertiesFromHandle", "CUresult", "*mut CUmemAllocationProp", "CUmemGenericAllocationHandle");
gen_unimplement!("cuMemRetainAllocationHandle", "CUresult", "*mut CUmemGenericAllocationHandle", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuMemFreeAsync", "CUresult", "CUdeviceptr", "CUstream");
gen_unimplement!("cuMemAllocAsync", "CUresult", "*mut CUdeviceptr", "size_t", "CUstream");
gen_unimplement!("cuMemPoolTrimTo", "CUresult", "CUmemoryPool", "size_t");
gen_unimplement!("cuMemPoolSetAttribute", "CUresult", "CUmemoryPool", "CUmemPool_attribute", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuMemPoolGetAttribute", "CUresult", "CUmemoryPool", "CUmemPool_attribute", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuMemPoolSetAccess", "CUresult", "CUmemoryPool", "*const CUmemAccessDesc", "size_t");
gen_unimplement!("cuMemPoolGetAccess", "CUresult", "*mut CUmemAccess_flags", "CUmemoryPool", "*mut CUmemLocation");
gen_unimplement!("cuMemPoolCreate", "CUresult", "*mut CUmemoryPool", "*const CUmemPoolProps");
gen_unimplement!("cuMemPoolDestroy", "CUresult", "CUmemoryPool");
gen_unimplement!("cuMemAllocFromPoolAsync", "CUresult", "*mut CUdeviceptr", "size_t", "CUmemoryPool", "CUstream");
gen_unimplement!("cuMemPoolExportToShareableHandle", "CUresult", "*mut ::std::os::raw::c_void", "CUmemoryPool", "CUmemAllocationHandleType", "::std::os::raw::c_ulonglong");
gen_unimplement!("cuMemPoolImportFromShareableHandle", "CUresult", "*mut CUmemoryPool", "*mut ::std::os::raw::c_void", "CUmemAllocationHandleType", "::std::os::raw::c_ulonglong");
gen_unimplement!("cuMemPoolExportPointer", "CUresult", "*mut CUmemPoolPtrExportData", "CUdeviceptr");
gen_unimplement!("cuMemPoolImportPointer", "CUresult", "*mut CUdeviceptr", "CUmemoryPool", "*mut CUmemPoolPtrExportData");
gen_unimplement!("cuPointerGetAttribute", "CUresult", "*mut ::std::os::raw::c_void", "CUpointer_attribute", "CUdeviceptr");
gen_unimplement!("cuMemPrefetchAsync", "CUresult", "CUdeviceptr", "size_t", "CUdevice", "CUstream");
gen_unimplement!("cuMemAdvise", "CUresult", "CUdeviceptr", "size_t", "CUmem_advise", "CUdevice");
gen_unimplement!("cuMemRangeGetAttribute", "CUresult", "*mut ::std::os::raw::c_void", "size_t", "CUmem_range_attribute", "CUdeviceptr", "size_t");
gen_unimplement!("cuMemRangeGetAttributes", "CUresult", "*mut *mut ::std::os::raw::c_void", "*mut size_t", "*mut CUmem_range_attribute", "size_t", "CUdeviceptr", "size_t");
gen_unimplement!("cuPointerSetAttribute", "CUresult", "*const ::std::os::raw::c_void", "CUpointer_attribute", "CUdeviceptr");
gen_unimplement!("cuPointerGetAttributes", "CUresult", "::std::os::raw::c_uint", "*mut CUpointer_attribute", "*mut *mut ::std::os::raw::c_void", "CUdeviceptr");
gen_unimplement!("cuStreamCreate", "CUresult", "*mut CUstream", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamCreateWithPriority", "CUresult", "*mut CUstream", "::std::os::raw::c_uint", "::std::os::raw::c_int");
gen_unimplement!("cuStreamGetPriority", "CUresult", "CUstream", "*mut ::std::os::raw::c_int");
gen_unimplement!("cuStreamGetFlags", "CUresult", "CUstream", "*mut ::std::os::raw::c_uint");
gen_unimplement!("cuStreamGetCtx", "CUresult", "CUstream", "*mut CUcontext");
gen_unimplement!("cuStreamWaitEvent", "CUresult", "CUstream", "CUevent", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamAddCallback", "CUresult", "CUstream", "CUstreamCallback", "*mut ::std::os::raw::c_void", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamBeginCapture_v2", "CUresult", "CUstream", "CUstreamCaptureMode");
gen_unimplement!("cuThreadExchangeStreamCaptureMode", "CUresult", "*mut CUstreamCaptureMode");
gen_unimplement!("cuStreamEndCapture", "CUresult", "CUstream", "*mut CUgraph");
gen_unimplement!("cuStreamIsCapturing", "CUresult", "CUstream", "*mut CUstreamCaptureStatus");
gen_unimplement!("cuStreamGetCaptureInfo", "CUresult", "CUstream", "*mut CUstreamCaptureStatus", "*mut cuuint64_t");
gen_unimplement!("cuStreamGetCaptureInfo_v2", "CUresult", "CUstream", "*mut CUstreamCaptureStatus", "*mut cuuint64_t", "*mut CUgraph", "*mut *const CUgraphNode", "*mut size_t");
gen_unimplement!("cuStreamUpdateCaptureDependencies", "CUresult", "CUstream", "*mut CUgraphNode", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamAttachMemAsync", "CUresult", "CUstream", "CUdeviceptr", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamQuery", "CUresult", "CUstream");
gen_unimplement!("cuStreamSynchronize", "CUresult", "CUstream");
gen_unimplement!("cuStreamDestroy_v2", "CUresult", "CUstream");
gen_unimplement!("cuStreamCopyAttributes", "CUresult", "CUstream", "CUstream");
gen_unimplement!("cuStreamGetAttribute", "CUresult", "CUstream", "CUstreamAttrID", "*mut CUstreamAttrValue");
gen_unimplement!("cuStreamSetAttribute", "CUresult", "CUstream", "CUstreamAttrID", "*const CUstreamAttrValue");
gen_unimplement!("cuEventCreate", "CUresult", "*mut CUevent", "::std::os::raw::c_uint");
gen_unimplement!("cuEventRecord", "CUresult", "CUevent", "CUstream");
gen_unimplement!("cuEventRecordWithFlags", "CUresult", "CUevent", "CUstream", "::std::os::raw::c_uint");
gen_unimplement!("cuEventQuery", "CUresult", "CUevent");
gen_unimplement!("cuEventSynchronize", "CUresult", "CUevent");
gen_unimplement!("cuEventDestroy_v2", "CUresult", "CUevent");
gen_unimplement!("cuEventElapsedTime", "CUresult", "*mut f32", "CUevent", "CUevent");
gen_unimplement!("cuImportExternalMemory", "CUresult", "*mut CUexternalMemory", "*const CUDA_EXTERNAL_MEMORY_HANDLE_DESC");
gen_unimplement!("cuExternalMemoryGetMappedBuffer", "CUresult", "*mut CUdeviceptr", "CUexternalMemory", "*const CUDA_EXTERNAL_MEMORY_BUFFER_DESC");
gen_unimplement!("cuExternalMemoryGetMappedMipmappedArray", "CUresult", "*mut CUmipmappedArray", "CUexternalMemory", "*const CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC");
gen_unimplement!("cuDestroyExternalMemory", "CUresult", "CUexternalMemory");
gen_unimplement!("cuImportExternalSemaphore", "CUresult", "*mut CUexternalSemaphore", "*const CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC");
gen_unimplement!("cuSignalExternalSemaphoresAsync", "CUresult", "*const CUexternalSemaphore", "*const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS", "::std::os::raw::c_uint", "CUstream");
gen_unimplement!("cuWaitExternalSemaphoresAsync", "CUresult", "*const CUexternalSemaphore", "*const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS", "::std::os::raw::c_uint", "CUstream");
gen_unimplement!("cuDestroyExternalSemaphore", "CUresult", "CUexternalSemaphore");
gen_unimplement!("cuStreamWaitValue32", "CUresult", "CUstream", "CUdeviceptr", "cuuint32_t", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamWaitValue64", "CUresult", "CUstream", "CUdeviceptr", "cuuint64_t", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamWriteValue32", "CUresult", "CUstream", "CUdeviceptr", "cuuint32_t", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamWriteValue64", "CUresult", "CUstream", "CUdeviceptr", "cuuint64_t", "::std::os::raw::c_uint");
gen_unimplement!("cuStreamBatchMemOp", "CUresult", "CUstream", "::std::os::raw::c_uint", "*mut CUstreamBatchMemOpParams", "::std::os::raw::c_uint");
gen_unimplement!("cuFuncGetAttribute", "CUresult", "*mut ::std::os::raw::c_int", "CUfunction_attribute", "CUfunction");
gen_unimplement!("cuFuncSetAttribute", "CUresult", "CUfunction", "CUfunction_attribute", "::std::os::raw::c_int");
gen_unimplement!("cuFuncSetCacheConfig", "CUresult", "CUfunction", "CUfunc_cache");
gen_unimplement!("cuFuncSetSharedMemConfig", "CUresult", "CUfunction", "CUsharedconfig");
gen_unimplement!("cuFuncGetModule", "CUresult", "*mut CUmodule", "CUfunction");
gen_unimplement!("cuLaunchKernel", "CUresult", "CUfunction", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "CUstream", "*mut *mut ::std::os::raw::c_void", "*mut *mut ::std::os::raw::c_void");
gen_unimplement!("cuLaunchCooperativeKernel", "CUresult", "CUfunction", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "CUstream", "*mut *mut ::std::os::raw::c_void");
gen_unimplement!("cuLaunchCooperativeKernelMultiDevice", "CUresult", "*mut CUDA_LAUNCH_PARAMS", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cuLaunchHostFunc", "CUresult", "CUstream", "CUhostFn", "*mut ::std::os::raw::c_void");
gen_unimplement!("cuFuncSetBlockShape", "CUresult", "CUfunction", "::std::os::raw::c_int", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cuFuncSetSharedSize", "CUresult", "CUfunction", "::std::os::raw::c_uint");
gen_unimplement!("cuParamSetSize", "CUresult", "CUfunction", "::std::os::raw::c_uint");
gen_unimplement!("cuParamSeti", "CUresult", "CUfunction", "::std::os::raw::c_int", "::std::os::raw::c_uint");
gen_unimplement!("cuParamSetf", "CUresult", "CUfunction", "::std::os::raw::c_int", "f32");
gen_unimplement!("cuParamSetv", "CUresult", "CUfunction", "::std::os::raw::c_int", "*mut ::std::os::raw::c_void", "::std::os::raw::c_uint");
gen_unimplement!("cuLaunch", "CUresult", "CUfunction");
gen_unimplement!("cuLaunchGrid", "CUresult", "CUfunction", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cuLaunchGridAsync", "CUresult", "CUfunction", "::std::os::raw::c_int", "::std::os::raw::c_int", "CUstream");
gen_unimplement!("cuParamSetTexRef", "CUresult", "CUfunction", "::std::os::raw::c_int", "CUtexref");
gen_unimplement!("cuGraphCreate", "CUresult", "*mut CUgraph", "::std::os::raw::c_uint");
gen_unimplement!("cuGraphAddKernelNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "*const CUDA_KERNEL_NODE_PARAMS");
gen_unimplement!("cuGraphKernelNodeGetParams", "CUresult", "CUgraphNode", "*mut CUDA_KERNEL_NODE_PARAMS");
gen_unimplement!("cuGraphKernelNodeSetParams", "CUresult", "CUgraphNode", "*const CUDA_KERNEL_NODE_PARAMS");
gen_unimplement!("cuGraphAddMemcpyNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "*const CUDA_MEMCPY3D", "CUcontext");
gen_unimplement!("cuGraphMemcpyNodeGetParams", "CUresult", "CUgraphNode", "*mut CUDA_MEMCPY3D");
gen_unimplement!("cuGraphMemcpyNodeSetParams", "CUresult", "CUgraphNode", "*const CUDA_MEMCPY3D");
gen_unimplement!("cuGraphAddMemsetNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "*const CUDA_MEMSET_NODE_PARAMS", "CUcontext");
gen_unimplement!("cuGraphMemsetNodeGetParams", "CUresult", "CUgraphNode", "*mut CUDA_MEMSET_NODE_PARAMS");
gen_unimplement!("cuGraphMemsetNodeSetParams", "CUresult", "CUgraphNode", "*const CUDA_MEMSET_NODE_PARAMS");
gen_unimplement!("cuGraphAddHostNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "*const CUDA_HOST_NODE_PARAMS");
gen_unimplement!("cuGraphHostNodeGetParams", "CUresult", "CUgraphNode", "*mut CUDA_HOST_NODE_PARAMS");
gen_unimplement!("cuGraphHostNodeSetParams", "CUresult", "CUgraphNode", "*const CUDA_HOST_NODE_PARAMS");
gen_unimplement!("cuGraphAddChildGraphNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "CUgraph");
gen_unimplement!("cuGraphChildGraphNodeGetGraph", "CUresult", "CUgraphNode", "*mut CUgraph");
gen_unimplement!("cuGraphAddEmptyNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t");
gen_unimplement!("cuGraphAddEventRecordNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "CUevent");
gen_unimplement!("cuGraphEventRecordNodeGetEvent", "CUresult", "CUgraphNode", "*mut CUevent");
gen_unimplement!("cuGraphEventRecordNodeSetEvent", "CUresult", "CUgraphNode", "CUevent");
gen_unimplement!("cuGraphAddEventWaitNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "CUevent");
gen_unimplement!("cuGraphEventWaitNodeGetEvent", "CUresult", "CUgraphNode", "*mut CUevent");
gen_unimplement!("cuGraphEventWaitNodeSetEvent", "CUresult", "CUgraphNode", "CUevent");
gen_unimplement!("cuGraphAddExternalSemaphoresSignalNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "*const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS");
gen_unimplement!("cuGraphExternalSemaphoresSignalNodeGetParams", "CUresult", "CUgraphNode", "*mut CUDA_EXT_SEM_SIGNAL_NODE_PARAMS");
gen_unimplement!("cuGraphExternalSemaphoresSignalNodeSetParams", "CUresult", "CUgraphNode", "*const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS");
gen_unimplement!("cuGraphAddExternalSemaphoresWaitNode", "CUresult", "*mut CUgraphNode", "CUgraph", "*const CUgraphNode", "size_t", "*const CUDA_EXT_SEM_WAIT_NODE_PARAMS");
gen_unimplement!("cuGraphExternalSemaphoresWaitNodeGetParams", "CUresult", "CUgraphNode", "*mut CUDA_EXT_SEM_WAIT_NODE_PARAMS");
gen_unimplement!("cuGraphExternalSemaphoresWaitNodeSetParams", "CUresult", "CUgraphNode", "*const CUDA_EXT_SEM_WAIT_NODE_PARAMS");
gen_unimplement!("cuGraphClone", "CUresult", "*mut CUgraph", "CUgraph");
gen_unimplement!("cuGraphNodeFindInClone", "CUresult", "*mut CUgraphNode", "CUgraphNode", "CUgraph");
gen_unimplement!("cuGraphNodeGetType", "CUresult", "CUgraphNode", "*mut CUgraphNodeType");
gen_unimplement!("cuGraphGetNodes", "CUresult", "CUgraph", "*mut CUgraphNode", "*mut size_t");
gen_unimplement!("cuGraphGetRootNodes", "CUresult", "CUgraph", "*mut CUgraphNode", "*mut size_t");
gen_unimplement!("cuGraphGetEdges", "CUresult", "CUgraph", "*mut CUgraphNode", "*mut CUgraphNode", "*mut size_t");
gen_unimplement!("cuGraphNodeGetDependencies", "CUresult", "CUgraphNode", "*mut CUgraphNode", "*mut size_t");
gen_unimplement!("cuGraphNodeGetDependentNodes", "CUresult", "CUgraphNode", "*mut CUgraphNode", "*mut size_t");
gen_unimplement!("cuGraphAddDependencies", "CUresult", "CUgraph", "*const CUgraphNode", "*const CUgraphNode", "size_t");
gen_unimplement!("cuGraphRemoveDependencies", "CUresult", "CUgraph", "*const CUgraphNode", "*const CUgraphNode", "size_t");
gen_unimplement!("cuGraphDestroyNode", "CUresult", "CUgraphNode");
gen_unimplement!("cuGraphInstantiate_v2", "CUresult", "*mut CUgraphExec", "CUgraph", "*mut CUgraphNode", "*mut ::std::os::raw::c_char", "size_t");
gen_unimplement!("cuGraphExecKernelNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "*const CUDA_KERNEL_NODE_PARAMS");
gen_unimplement!("cuGraphExecMemcpyNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "*const CUDA_MEMCPY3D", "CUcontext");
gen_unimplement!("cuGraphExecMemsetNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "*const CUDA_MEMSET_NODE_PARAMS", "CUcontext");
gen_unimplement!("cuGraphExecHostNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "*const CUDA_HOST_NODE_PARAMS");
gen_unimplement!("cuGraphExecChildGraphNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "CUgraph");
gen_unimplement!("cuGraphExecEventRecordNodeSetEvent", "CUresult", "CUgraphExec", "CUgraphNode", "CUevent");
gen_unimplement!("cuGraphExecEventWaitNodeSetEvent", "CUresult", "CUgraphExec", "CUgraphNode", "CUevent");
gen_unimplement!("cuGraphExecExternalSemaphoresSignalNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "*const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS");
gen_unimplement!("cuGraphExecExternalSemaphoresWaitNodeSetParams", "CUresult", "CUgraphExec", "CUgraphNode", "*const CUDA_EXT_SEM_WAIT_NODE_PARAMS");
gen_unimplement!("cuGraphUpload", "CUresult", "CUgraphExec", "CUstream");
gen_unimplement!("cuGraphLaunch", "CUresult", "CUgraphExec", "CUstream");
gen_unimplement!("cuGraphExecDestroy", "CUresult", "CUgraphExec");
gen_unimplement!("cuGraphDestroy", "CUresult", "CUgraph");
gen_unimplement!("cuGraphExecUpdate", "CUresult", "CUgraphExec", "CUgraph", "*mut CUgraphNode", "*mut CUgraphExecUpdateResult");
gen_unimplement!("cuGraphKernelNodeCopyAttributes", "CUresult", "CUgraphNode", "CUgraphNode");
gen_unimplement!("cuGraphKernelNodeGetAttribute", "CUresult", "CUgraphNode", "CUkernelNodeAttrID", "*mut CUkernelNodeAttrValue");
gen_unimplement!("cuGraphKernelNodeSetAttribute", "CUresult", "CUgraphNode", "CUkernelNodeAttrID", "*const CUkernelNodeAttrValue");
gen_unimplement!("cuGraphDebugDotPrint", "CUresult", "CUgraph", "*const ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("cuUserObjectCreate", "CUresult", "*mut CUuserObject", "*mut ::std::os::raw::c_void", "CUhostFn", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cuUserObjectRetain", "CUresult", "CUuserObject", "::std::os::raw::c_uint");
gen_unimplement!("cuUserObjectRelease", "CUresult", "CUuserObject", "::std::os::raw::c_uint");
gen_unimplement!("cuGraphRetainUserObject", "CUresult", "CUgraph", "CUuserObject", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cuGraphReleaseUserObject", "CUresult", "CUgraph", "CUuserObject", "::std::os::raw::c_uint");
gen_unimplement!("cuOccupancyMaxActiveBlocksPerMultiprocessor", "CUresult", "*mut ::std::os::raw::c_int", "CUfunction", "::std::os::raw::c_int", "size_t");
gen_unimplement!("cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags", "CUresult", "*mut ::std::os::raw::c_int", "CUfunction", "::std::os::raw::c_int", "size_t", "::std::os::raw::c_uint");
gen_unimplement!("cuOccupancyMaxPotentialBlockSize", "CUresult", "*mut ::std::os::raw::c_int", "*mut ::std::os::raw::c_int", "CUfunction", "CUoccupancyB2DSize", "size_t", "::std::os::raw::c_int");
gen_unimplement!("cuOccupancyMaxPotentialBlockSizeWithFlags", "CUresult", "*mut ::std::os::raw::c_int", "*mut ::std::os::raw::c_int", "CUfunction", "CUoccupancyB2DSize", "size_t", "::std::os::raw::c_int", "::std::os::raw::c_uint");
gen_unimplement!("cuOccupancyAvailableDynamicSMemPerBlock", "CUresult", "*mut size_t", "CUfunction", "::std::os::raw::c_int", "::std::os::raw::c_int");
gen_unimplement!("cuTexRefSetArray", "CUresult", "CUtexref", "CUarray", "::std::os::raw::c_uint");
gen_unimplement!("cuTexRefSetMipmappedArray", "CUresult", "CUtexref", "CUmipmappedArray", "::std::os::raw::c_uint");
gen_unimplement!("cuTexRefSetAddress_v2", "CUresult", "*mut size_t", "CUtexref", "CUdeviceptr", "size_t");
gen_unimplement!("cuTexRefSetAddress2D_v3", "CUresult", "CUtexref", "*const CUDA_ARRAY_DESCRIPTOR", "CUdeviceptr", "size_t");
gen_unimplement!("cuTexRefSetFormat", "CUresult", "CUtexref", "CUarray_format", "::std::os::raw::c_int");
gen_unimplement!("cuTexRefSetAddressMode", "CUresult", "CUtexref", "::std::os::raw::c_int", "CUaddress_mode");
gen_unimplement!("cuTexRefSetFilterMode", "CUresult", "CUtexref", "CUfilter_mode");
gen_unimplement!("cuTexRefSetMipmapFilterMode", "CUresult", "CUtexref", "CUfilter_mode");
gen_unimplement!("cuTexRefSetMipmapLevelBias", "CUresult", "CUtexref", "f32");
gen_unimplement!("cuTexRefSetMipmapLevelClamp", "CUresult", "CUtexref", "f32", "f32");
gen_unimplement!("cuTexRefSetMaxAnisotropy", "CUresult", "CUtexref", "::std::os::raw::c_uint");
gen_unimplement!("cuTexRefSetBorderColor", "CUresult", "CUtexref", "*mut f32");
gen_unimplement!("cuTexRefSetFlags", "CUresult", "CUtexref", "::std::os::raw::c_uint");
gen_unimplement!("cuTexRefGetAddress_v2", "CUresult", "*mut CUdeviceptr", "CUtexref");
gen_unimplement!("cuTexRefGetArray", "CUresult", "*mut CUarray", "CUtexref");
gen_unimplement!("cuTexRefGetMipmappedArray", "CUresult", "*mut CUmipmappedArray", "CUtexref");
gen_unimplement!("cuTexRefGetAddressMode", "CUresult", "*mut CUaddress_mode", "CUtexref", "::std::os::raw::c_int");
gen_unimplement!("cuTexRefGetFilterMode", "CUresult", "*mut CUfilter_mode", "CUtexref");
gen_unimplement!("cuTexRefGetFormat", "CUresult", "*mut CUarray_format", "*mut ::std::os::raw::c_int", "CUtexref");
gen_unimplement!("cuTexRefGetMipmapFilterMode", "CUresult", "*mut CUfilter_mode", "CUtexref");
gen_unimplement!("cuTexRefGetMipmapLevelBias", "CUresult", "*mut f32", "CUtexref");
gen_unimplement!("cuTexRefGetMipmapLevelClamp", "CUresult", "*mut f32", "*mut f32", "CUtexref");
gen_unimplement!("cuTexRefGetMaxAnisotropy", "CUresult", "*mut ::std::os::raw::c_int", "CUtexref");
gen_unimplement!("cuTexRefGetBorderColor", "CUresult", "*mut f32", "CUtexref");
gen_unimplement!("cuTexRefGetFlags", "CUresult", "*mut ::std::os::raw::c_uint", "CUtexref");
gen_unimplement!("cuTexRefCreate", "CUresult", "*mut CUtexref");
gen_unimplement!("cuTexRefDestroy", "CUresult", "CUtexref");
gen_unimplement!("cuSurfRefSetArray", "CUresult", "CUsurfref", "CUarray", "::std::os::raw::c_uint");
gen_unimplement!("cuSurfRefGetArray", "CUresult", "*mut CUarray", "CUsurfref");
gen_unimplement!("cuTexObjectCreate", "CUresult", "*mut CUtexObject", "*const CUDA_RESOURCE_DESC", "*const CUDA_TEXTURE_DESC", "*const CUDA_RESOURCE_VIEW_DESC");
gen_unimplement!("cuTexObjectDestroy", "CUresult", "CUtexObject");
gen_unimplement!("cuTexObjectGetResourceDesc", "CUresult", "*mut CUDA_RESOURCE_DESC", "CUtexObject");
gen_unimplement!("cuTexObjectGetTextureDesc", "CUresult", "*mut CUDA_TEXTURE_DESC", "CUtexObject");
gen_unimplement!("cuTexObjectGetResourceViewDesc", "CUresult", "*mut CUDA_RESOURCE_VIEW_DESC", "CUtexObject");
gen_unimplement!("cuSurfObjectCreate", "CUresult", "*mut CUsurfObject", "*const CUDA_RESOURCE_DESC");
gen_unimplement!("cuSurfObjectDestroy", "CUresult", "CUsurfObject");
gen_unimplement!("cuSurfObjectGetResourceDesc", "CUresult", "*mut CUDA_RESOURCE_DESC", "CUsurfObject");
gen_unimplement!("cuDeviceCanAccessPeer", "CUresult", "*mut ::std::os::raw::c_int", "CUdevice", "CUdevice");
gen_unimplement!("cuCtxEnablePeerAccess", "CUresult", "CUcontext", "::std::os::raw::c_uint");
gen_unimplement!("cuCtxDisablePeerAccess", "CUresult", "CUcontext");
gen_unimplement!("cuDeviceGetP2PAttribute", "CUresult", "*mut ::std::os::raw::c_int", "CUdevice_P2PAttribute", "CUdevice", "CUdevice");
gen_unimplement!("cuGraphicsUnregisterResource", "CUresult", "CUgraphicsResource");
gen_unimplement!("cuGraphicsSubResourceGetMappedArray", "CUresult", "*mut CUarray", "CUgraphicsResource", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("cuGraphicsResourceGetMappedMipmappedArray", "CUresult", "*mut CUmipmappedArray", "CUgraphicsResource");
gen_unimplement!("cuGraphicsResourceGetMappedPointer_v2", "CUresult", "*mut CUdeviceptr", "*mut size_t", "CUgraphicsResource");
gen_unimplement!("cuGraphicsResourceSetMapFlags_v2", "CUresult", "CUgraphicsResource", "::std::os::raw::c_uint");
gen_unimplement!("cuGraphicsMapResources", "CUresult", "::std::os::raw::c_uint", "*mut CUgraphicsResource", "CUstream");
gen_unimplement!("cuGraphicsUnmapResources", "CUresult", "::std::os::raw::c_uint", "*mut CUgraphicsResource", "CUstream");
gen_unimplement!("cuGetProcAddress", "CUresult", "*const ::std::os::raw::c_char", "*mut *mut ::std::os::raw::c_void", "::std::os::raw::c_int", "cuuint64_t");
gen_unimplement!("cuGetExportTable", "CUresult", "*mut *const ::std::os::raw::c_void", "*const CUuuid");
gen_unimplement!("cuFlushGPUDirectRDMAWrites", "CUresult", "CUflushGPUDirectRDMAWritesTarget", "CUflushGPUDirectRDMAWritesScope");
gen_unimplement!("cuProfilerInitialize", "CUresult", "*const ::std::os::raw::c_char", "*const ::std::os::raw::c_char", "CUoutput_mode");
gen_unimplement!("cuProfilerStart", "CUresult");
gen_unimplement!("cuProfilerStop", "CUresult");
