#![allow(non_snake_case)]
use super::*;
use cudasys::types::nvml::*;

gen_unimplement!("nvmlShutdown", "nvmlReturn_t");
gen_unimplement!("nvmlErrorString", "*const ::std::os::raw::c_char", "nvmlReturn_t");
gen_unimplement!("nvmlSystemGetDriverVersion", "nvmlReturn_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlSystemGetNVMLVersion", "nvmlReturn_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlSystemGetCudaDriverVersion", "nvmlReturn_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("nvmlSystemGetCudaDriverVersion_v2", "nvmlReturn_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("nvmlSystemGetProcessName", "nvmlReturn_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlUnitGetCount", "nvmlReturn_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlUnitGetHandleByIndex", "nvmlReturn_t", "::std::os::raw::c_uint", "*mut nvmlUnit_t");
gen_unimplement!("nvmlUnitGetUnitInfo", "nvmlReturn_t", "nvmlUnit_t", "*mut nvmlUnitInfo_t");
gen_unimplement!("nvmlUnitGetLedState", "nvmlReturn_t", "nvmlUnit_t", "*mut nvmlLedState_t");
gen_unimplement!("nvmlUnitGetPsuInfo", "nvmlReturn_t", "nvmlUnit_t", "*mut nvmlPSUInfo_t");
gen_unimplement!("nvmlUnitGetTemperature", "nvmlReturn_t", "nvmlUnit_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlUnitGetFanSpeedInfo", "nvmlReturn_t", "nvmlUnit_t", "*mut nvmlUnitFanSpeeds_t");
gen_unimplement!("nvmlUnitGetDevices", "nvmlReturn_t", "nvmlUnit_t", "*mut ::std::os::raw::c_uint", "*mut nvmlDevice_t");
gen_unimplement!("nvmlSystemGetHicVersion", "nvmlReturn_t", "*mut ::std::os::raw::c_uint", "*mut nvmlHwbcEntry_t");
gen_unimplement!("nvmlDeviceGetAttributes_v2", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlDeviceAttributes_t");
gen_unimplement!("nvmlDeviceGetHandleByIndex_v2", "nvmlReturn_t", "::std::os::raw::c_uint", "*mut nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetHandleBySerial", "nvmlReturn_t", "*const ::std::os::raw::c_char", "*mut nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetHandleByUUID", "nvmlReturn_t", "*const ::std::os::raw::c_char", "*mut nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetHandleByPciBusId_v2", "nvmlReturn_t", "*const ::std::os::raw::c_char", "*mut nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetName", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetBrand", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlBrandType_t");
gen_unimplement!("nvmlDeviceGetIndex", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetSerial", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMemoryAffinity", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_ulong", "nvmlAffinityScope_t");
gen_unimplement!("nvmlDeviceGetCpuAffinityWithinScope", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_ulong", "nvmlAffinityScope_t");
gen_unimplement!("nvmlDeviceGetCpuAffinity", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_ulong");
gen_unimplement!("nvmlDeviceSetCpuAffinity", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceClearCpuAffinity", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetTopologyCommonAncestor", "nvmlReturn_t", "nvmlDevice_t", "nvmlDevice_t", "*mut nvmlGpuTopologyLevel_t");
gen_unimplement!("nvmlDeviceGetTopologyNearestGpus", "nvmlReturn_t", "nvmlDevice_t", "nvmlGpuTopologyLevel_t", "*mut ::std::os::raw::c_uint", "*mut nvmlDevice_t");
gen_unimplement!("nvmlSystemGetTopologyGpuSet", "nvmlReturn_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetP2PStatus", "nvmlReturn_t", "nvmlDevice_t", "nvmlDevice_t", "nvmlGpuP2PCapsIndex_t", "*mut nvmlGpuP2PStatus_t");
gen_unimplement!("nvmlDeviceGetUUID", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetMdevUUID", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMinorNumber", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetBoardPartNumber", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetInforomVersion", "nvmlReturn_t", "nvmlDevice_t", "nvmlInforomObject_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetInforomImageVersion", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetInforomConfigurationChecksum", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceValidateInforom", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetDisplayMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetDisplayActive", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetPersistenceMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetPciInfo_v3", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlPciInfo_t");
gen_unimplement!("nvmlDeviceGetMaxPcieLinkGeneration", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMaxPcieLinkWidth", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetCurrPcieLinkGeneration", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetCurrPcieLinkWidth", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetPcieThroughput", "nvmlReturn_t", "nvmlDevice_t", "nvmlPcieUtilCounter_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetPcieReplayCounter", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetClockInfo", "nvmlReturn_t", "nvmlDevice_t", "nvmlClockType_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMaxClockInfo", "nvmlReturn_t", "nvmlDevice_t", "nvmlClockType_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetApplicationsClock", "nvmlReturn_t", "nvmlDevice_t", "nvmlClockType_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetDefaultApplicationsClock", "nvmlReturn_t", "nvmlDevice_t", "nvmlClockType_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceResetApplicationsClocks", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetClock", "nvmlReturn_t", "nvmlDevice_t", "nvmlClockType_t", "nvmlClockId_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMaxCustomerBoostClock", "nvmlReturn_t", "nvmlDevice_t", "nvmlClockType_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetSupportedMemoryClocks", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetSupportedGraphicsClocks", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetAutoBoostedClocksEnabled", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceSetAutoBoostedClocksEnabled", "nvmlReturn_t", "nvmlDevice_t", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceSetDefaultAutoBoostedClocksEnabled", "nvmlReturn_t", "nvmlDevice_t", "nvmlEnableState_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetFanSpeed", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetFanSpeed_v2", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetTemperature", "nvmlReturn_t", "nvmlDevice_t", "nvmlTemperatureSensors_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetTemperatureThreshold", "nvmlReturn_t", "nvmlDevice_t", "nvmlTemperatureThresholds_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceSetTemperatureThreshold", "nvmlReturn_t", "nvmlDevice_t", "nvmlTemperatureThresholds_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("nvmlDeviceGetPerformanceState", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlPstates_t");
gen_unimplement!("nvmlDeviceGetCurrentClocksThrottleReasons", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetSupportedClocksThrottleReasons", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetPowerState", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlPstates_t");
gen_unimplement!("nvmlDeviceGetPowerManagementMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetPowerManagementLimit", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetPowerManagementLimitConstraints", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetPowerManagementDefaultLimit", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetPowerUsage", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetTotalEnergyConsumption", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetEnforcedPowerLimit", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetGpuOperationMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlGpuOperationMode_t", "*mut nvmlGpuOperationMode_t");
gen_unimplement!("nvmlDeviceGetMemoryInfo", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlMemory_t");
gen_unimplement!("nvmlDeviceGetComputeMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlComputeMode_t");
gen_unimplement!("nvmlDeviceGetCudaComputeCapability", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_int", "*mut ::std::os::raw::c_int");
gen_unimplement!("nvmlDeviceGetEccMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetBoardId", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMultiGpuBoard", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetTotalEccErrors", "nvmlReturn_t", "nvmlDevice_t", "nvmlMemoryErrorType_t", "nvmlEccCounterType_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetDetailedEccErrors", "nvmlReturn_t", "nvmlDevice_t", "nvmlMemoryErrorType_t", "nvmlEccCounterType_t", "*mut nvmlEccErrorCounts_t");
gen_unimplement!("nvmlDeviceGetMemoryErrorCounter", "nvmlReturn_t", "nvmlDevice_t", "nvmlMemoryErrorType_t", "nvmlEccCounterType_t", "nvmlMemoryLocation_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetUtilizationRates", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlUtilization_t");
gen_unimplement!("nvmlDeviceGetEncoderUtilization", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetEncoderCapacity", "nvmlReturn_t", "nvmlDevice_t", "nvmlEncoderType_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetEncoderStats", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetEncoderSessions", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlEncoderSessionInfo_t");
gen_unimplement!("nvmlDeviceGetDecoderUtilization", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetFBCStats", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlFBCStats_t");
gen_unimplement!("nvmlDeviceGetFBCSessions", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlFBCSessionInfo_t");
gen_unimplement!("nvmlDeviceGetDriverModel", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlDriverModel_t", "*mut nvmlDriverModel_t");
gen_unimplement!("nvmlDeviceGetVbiosVersion", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetBridgeChipInfo", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlBridgeChipHierarchy_t");
gen_unimplement!("nvmlDeviceGetComputeRunningProcesses_v2", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlProcessInfo_t");
gen_unimplement!("nvmlDeviceGetGraphicsRunningProcesses_v2", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlProcessInfo_t");
gen_unimplement!("nvmlDeviceOnSameBoard", "nvmlReturn_t", "nvmlDevice_t", "nvmlDevice_t", "*mut ::std::os::raw::c_int");
gen_unimplement!("nvmlDeviceGetAPIRestriction", "nvmlReturn_t", "nvmlDevice_t", "nvmlRestrictedAPI_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetSamples", "nvmlReturn_t", "nvmlDevice_t", "nvmlSamplingType_t", "::std::os::raw::c_ulonglong", "*mut nvmlValueType_t", "*mut ::std::os::raw::c_uint", "*mut nvmlSample_t");
gen_unimplement!("nvmlDeviceGetBAR1MemoryInfo", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlBAR1Memory_t");
gen_unimplement!("nvmlDeviceGetViolationStatus", "nvmlReturn_t", "nvmlDevice_t", "nvmlPerfPolicyType_t", "*mut nvmlViolationTime_t");
gen_unimplement!("nvmlDeviceGetAccountingMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetAccountingStats", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlAccountingStats_t");
gen_unimplement!("nvmlDeviceGetAccountingPids", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetAccountingBufferSize", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetRetiredPages", "nvmlReturn_t", "nvmlDevice_t", "nvmlPageRetirementCause_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetRetiredPages_v2", "nvmlReturn_t", "nvmlDevice_t", "nvmlPageRetirementCause_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_ulonglong", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetRetiredPagesPendingStatus", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetRemappedRows", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetRowRemapperHistogram", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlRowRemapperHistogramValues_t");
gen_unimplement!("nvmlDeviceGetArchitecture", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlDeviceArchitecture_t");
gen_unimplement!("nvmlUnitSetLedState", "nvmlReturn_t", "nvmlUnit_t", "nvmlLedColor_t");
gen_unimplement!("nvmlDeviceSetPersistenceMode", "nvmlReturn_t", "nvmlDevice_t", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceSetComputeMode", "nvmlReturn_t", "nvmlDevice_t", "nvmlComputeMode_t");
gen_unimplement!("nvmlDeviceSetEccMode", "nvmlReturn_t", "nvmlDevice_t", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceClearEccErrorCounts", "nvmlReturn_t", "nvmlDevice_t", "nvmlEccCounterType_t");
gen_unimplement!("nvmlDeviceSetDriverModel", "nvmlReturn_t", "nvmlDevice_t", "nvmlDriverModel_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceSetGpuLockedClocks", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceResetGpuLockedClocks", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceSetMemoryLockedClocks", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceResetMemoryLockedClocks", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceSetApplicationsClocks", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceSetPowerManagementLimit", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceSetGpuOperationMode", "nvmlReturn_t", "nvmlDevice_t", "nvmlGpuOperationMode_t");
gen_unimplement!("nvmlDeviceSetAPIRestriction", "nvmlReturn_t", "nvmlDevice_t", "nvmlRestrictedAPI_t", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceSetAccountingMode", "nvmlReturn_t", "nvmlDevice_t", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceClearAccountingPids", "nvmlReturn_t", "nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetNvLinkState", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceGetNvLinkVersion", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetNvLinkCapability", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "nvmlNvLinkCapability_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetNvLinkRemotePciInfo_v2", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlPciInfo_t");
gen_unimplement!("nvmlDeviceGetNvLinkErrorCounter", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "nvmlNvLinkErrorCounter_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceResetNvLinkErrorCounters", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceSetNvLinkUtilizationControl", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "*mut nvmlNvLinkUtilizationControl_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetNvLinkUtilizationControl", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "*mut nvmlNvLinkUtilizationControl_t");
gen_unimplement!("nvmlDeviceGetNvLinkUtilizationCounter", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_ulonglong", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceFreezeNvLinkUtilizationCounter", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceResetNvLinkUtilizationCounter", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint");
gen_unimplement!("nvmlEventSetCreate", "nvmlReturn_t", "*mut nvmlEventSet_t");
gen_unimplement!("nvmlDeviceRegisterEvents", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_ulonglong", "nvmlEventSet_t");
gen_unimplement!("nvmlDeviceGetSupportedEventTypes", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlEventSetWait_v2", "nvmlReturn_t", "nvmlEventSet_t", "*mut nvmlEventData_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlEventSetFree", "nvmlReturn_t", "nvmlEventSet_t");
gen_unimplement!("nvmlDeviceModifyDrainState", "nvmlReturn_t", "*mut nvmlPciInfo_t", "nvmlEnableState_t");
gen_unimplement!("nvmlDeviceQueryDrainState", "nvmlReturn_t", "*mut nvmlPciInfo_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlDeviceRemoveGpu_v2", "nvmlReturn_t", "*mut nvmlPciInfo_t", "nvmlDetachGpuState_t", "nvmlPcieLinkState_t");
gen_unimplement!("nvmlDeviceDiscoverGpus", "nvmlReturn_t", "*mut nvmlPciInfo_t");
gen_unimplement!("nvmlDeviceGetFieldValues", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_int", "*mut nvmlFieldValue_t");
gen_unimplement!("nvmlDeviceGetVirtualizationMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlGpuVirtualizationMode_t");
gen_unimplement!("nvmlDeviceGetHostVgpuMode", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlHostVgpuMode_t");
gen_unimplement!("nvmlDeviceSetVirtualizationMode", "nvmlReturn_t", "nvmlDevice_t", "nvmlGpuVirtualizationMode_t");
gen_unimplement!("nvmlDeviceGetGridLicensableFeatures_v3", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlGridLicensableFeatures_t");
gen_unimplement!("nvmlDeviceGetProcessUtilization", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlProcessUtilizationSample_t", "*mut ::std::os::raw::c_uint", "::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlDeviceGetSupportedVgpus", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlVgpuTypeId_t");
gen_unimplement!("nvmlDeviceGetCreatableVgpus", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlVgpuTypeId_t");
gen_unimplement!("nvmlVgpuTypeGetClass", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_char", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetName", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_char", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetGpuInstanceProfileId", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetDeviceID", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_ulonglong", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlVgpuTypeGetFramebufferSize", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlVgpuTypeGetNumDisplayHeads", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetResolution", "nvmlReturn_t", "nvmlVgpuTypeId_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetLicense", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetFrameRateLimit", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetMaxInstances", "nvmlReturn_t", "nvmlDevice_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuTypeGetMaxInstancesPerVm", "nvmlReturn_t", "nvmlVgpuTypeId_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetActiveVgpus", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut nvmlVgpuInstance_t");
gen_unimplement!("nvmlVgpuInstanceGetVmID", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint", "*mut nvmlVgpuVmIdType_t");
gen_unimplement!("nvmlVgpuInstanceGetUUID", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetVmDriverVersion", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_char", "::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetFbUsage", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_ulonglong");
gen_unimplement!("nvmlVgpuInstanceGetLicenseStatus", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetType", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut nvmlVgpuTypeId_t");
gen_unimplement!("nvmlVgpuInstanceGetFrameRateLimit", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetEccMode", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlVgpuInstanceGetEncoderCapacity", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceSetEncoderCapacity", "nvmlReturn_t", "nvmlVgpuInstance_t", "::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetEncoderStats", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetEncoderSessions", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint", "*mut nvmlEncoderSessionInfo_t");
gen_unimplement!("nvmlVgpuInstanceGetFBCStats", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut nvmlFBCStats_t");
gen_unimplement!("nvmlVgpuInstanceGetFBCSessions", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint", "*mut nvmlFBCSessionInfo_t");
gen_unimplement!("nvmlVgpuInstanceGetGpuInstanceId", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetMetadata", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut nvmlVgpuMetadata_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetVgpuMetadata", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlVgpuPgpuMetadata_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlGetVgpuCompatibility", "nvmlReturn_t", "*mut nvmlVgpuMetadata_t", "*mut nvmlVgpuPgpuMetadata_t", "*mut nvmlVgpuPgpuCompatibility_t");
gen_unimplement!("nvmlDeviceGetPgpuMetadataString", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_char", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlGetVgpuVersion", "nvmlReturn_t", "*mut nvmlVgpuVersion_t", "*mut nvmlVgpuVersion_t");
gen_unimplement!("nvmlSetVgpuVersion", "nvmlReturn_t", "*mut nvmlVgpuVersion_t");
gen_unimplement!("nvmlDeviceGetVgpuUtilization", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_ulonglong", "*mut nvmlValueType_t", "*mut ::std::os::raw::c_uint", "*mut nvmlVgpuInstanceUtilizationSample_t");
gen_unimplement!("nvmlDeviceGetVgpuProcessUtilization", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_ulonglong", "*mut ::std::os::raw::c_uint", "*mut nvmlVgpuProcessUtilizationSample_t");
gen_unimplement!("nvmlVgpuInstanceGetAccountingMode", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut nvmlEnableState_t");
gen_unimplement!("nvmlVgpuInstanceGetAccountingPids", "nvmlReturn_t", "nvmlVgpuInstance_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlVgpuInstanceGetAccountingStats", "nvmlReturn_t", "nvmlVgpuInstance_t", "::std::os::raw::c_uint", "*mut nvmlAccountingStats_t");
gen_unimplement!("nvmlVgpuInstanceClearAccountingPids", "nvmlReturn_t", "nvmlVgpuInstance_t");
gen_unimplement!("nvmlGetExcludedDeviceCount", "nvmlReturn_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlGetExcludedDeviceInfoByIndex", "nvmlReturn_t", "::std::os::raw::c_uint", "*mut nvmlExcludedDeviceInfo_t");
gen_unimplement!("nvmlDeviceSetMigMode", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlReturn_t");
gen_unimplement!("nvmlDeviceGetMigMode", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetGpuInstanceProfileInfo", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlGpuInstanceProfileInfo_t");
gen_unimplement!("nvmlDeviceGetGpuInstancePossiblePlacements", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlGpuInstancePlacement_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetGpuInstanceRemainingCapacity", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceCreateGpuInstance", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlGpuInstance_t");
gen_unimplement!("nvmlDeviceCreateGpuInstanceWithPlacement", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*const nvmlGpuInstancePlacement_t", "*mut nvmlGpuInstance_t");
gen_unimplement!("nvmlGpuInstanceDestroy", "nvmlReturn_t", "nvmlGpuInstance_t");
gen_unimplement!("nvmlDeviceGetGpuInstances", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlGpuInstance_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetGpuInstanceById", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlGpuInstance_t");
gen_unimplement!("nvmlGpuInstanceGetInfo", "nvmlReturn_t", "nvmlGpuInstance_t", "*mut nvmlGpuInstanceInfo_t");
gen_unimplement!("nvmlGpuInstanceGetComputeInstanceProfileInfo", "nvmlReturn_t", "nvmlGpuInstance_t", "::std::os::raw::c_uint", "::std::os::raw::c_uint", "*mut nvmlComputeInstanceProfileInfo_t");
gen_unimplement!("nvmlGpuInstanceGetComputeInstanceRemainingCapacity", "nvmlReturn_t", "nvmlGpuInstance_t", "::std::os::raw::c_uint", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlGpuInstanceCreateComputeInstance", "nvmlReturn_t", "nvmlGpuInstance_t", "::std::os::raw::c_uint", "*mut nvmlComputeInstance_t");
gen_unimplement!("nvmlComputeInstanceDestroy", "nvmlReturn_t", "nvmlComputeInstance_t");
gen_unimplement!("nvmlGpuInstanceGetComputeInstances", "nvmlReturn_t", "nvmlGpuInstance_t", "::std::os::raw::c_uint", "*mut nvmlComputeInstance_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlGpuInstanceGetComputeInstanceById", "nvmlReturn_t", "nvmlGpuInstance_t", "::std::os::raw::c_uint", "*mut nvmlComputeInstance_t");
gen_unimplement!("nvmlComputeInstanceGetInfo_v2", "nvmlReturn_t", "nvmlComputeInstance_t", "*mut nvmlComputeInstanceInfo_t");
gen_unimplement!("nvmlDeviceIsMigDeviceHandle", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetGpuInstanceId", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetComputeInstanceId", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMaxMigDeviceCount", "nvmlReturn_t", "nvmlDevice_t", "*mut ::std::os::raw::c_uint");
gen_unimplement!("nvmlDeviceGetMigDeviceHandleByIndex", "nvmlReturn_t", "nvmlDevice_t", "::std::os::raw::c_uint", "*mut nvmlDevice_t");
gen_unimplement!("nvmlDeviceGetDeviceHandleFromMigDeviceHandle", "nvmlReturn_t", "nvmlDevice_t", "*mut nvmlDevice_t");
