[package]
name = "hookgen"
version.workspace = true
edition.workspace = true

[dependencies]
hookdef = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
