.PHONY: all clean log_breakpoint vanilla

all: log_breakpoint vanilla

log_breakpoint:
	$(MAKE) -C log_breakpoint

vanilla:
	$(MAKE) -C vanilla

clean:
	$(MAKE) -C log_breakpoint clean
	$(MAKE) -C vanilla clean
