blocking_type_dict = {
    "__cudaPushCallConfiguration": "NonBlocking",
    "__cudaPopCallConfiguration": "NonBlocking",
    "cublasCreate_v2": "NonBlocking",
    "cublasGetMathMode": "NonBlocking",
    "cublasGemmEx": "GPUBlocking",
    "cublasSetMathMode": "NonBlocking",
    "cublasSetStream_v2": "NonBlocking",
    "cublasSgemm_v2": "GPUBlocking",
    "cublasSgemmStridedBatched": "GPUBlocking",
    "cublasGemmStridedBatchedEx": "GPUBlocking",
    "cudaDeviceGetAttribute": "NonBlocking",
    "cudaFree": "GPUBlocking",
    "cudaGetDevice": "NonBlocking",
    "cudaGetLastError": "NonBlocking",
    "cudaLaunchKernel": "GPUBlocking",
    "cudaMalloc": "GPUBlocking",
    "cudaMemcpyAsync": "GPUBlocking",
    "cudaMemcpyAsyncDeviceToDevice": "GPUBlocking",
    "cudaMemcpyAsyncDeviceToHost": "GPUBlocking",
    "cudaMemcpyAsyncHostToDevice": "GPUBlocking",
    "cudaMemsetAsync": "GPUBlocking",
    "cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags": "NonBlocking",
    "cudaPeekAtLastError": "NonBlocking",
    "cudaSetDevice": "NonBlocking",
    "cudaStreamIsCapturing": "CPUBlocking",
    "cudaStreamSynchronize": "CPUBlocking",
    "cudnnBatchNormalizationBackwardEx": "GPUBlocking",
    "cudnnBatchNormalizationForwardInference": "GPUBlocking",
    "cudnnBatchNormalizationForwardTrainingEx": "GPUBlocking",
    "cudnnCreate": "NonBlocking",
    "cudnnConvolutionBackwardData": "GPUBlocking",
    "cudnnConvolutionBackwardFilter": "GPUBlocking",
    "cudnnConvolutionForward": "GPUBlocking",
    "cudnnCreateConvolutionDescriptor": "NonBlocking",
    "cudnnCreateFilterDescriptor": "NonBlocking",
    "cudnnCreateTensorDescriptor": "NonBlocking",
    "cudnnDestroyConvolutionDescriptor": "NonBlocking",
    "cudnnDestroyFilterDescriptor": "NonBlocking",
    "cudnnDestroyTensorDescriptor": "NonBlocking",
    "cudnnGetBatchNormalizationBackwardExWorkspaceSize": "NonBlocking",
    "cudnnGetBatchNormalizationForwardTrainingExWorkspaceSize": "NonBlocking",
    "cudnnGetBatchNormalizationTrainingExReserveSpaceSize": "NonBlocking",
    "cudnnGetConvolutionBackwardDataAlgorithm_v7": "NonBlocking",
    "cudnnGetConvolutionBackwardFilterAlgorithm_v7": "NonBlocking",
    "cudnnGetConvolutionForwardAlgorithm_v7": "NonBlocking",
    "cudnnInitTransformDest": "NonBlocking",
    "cudnnSetConvolutionGroupCount": "NonBlocking",
    "cudnnSetConvolutionMathType": "NonBlocking",
    "cudnnSetConvolutionNdDescriptor": "NonBlocking",
    "cudnnSetFilterNdDescriptor": "NonBlocking",
    "cudnnSetTensorNdDescriptor": "NonBlocking",
    "cudnnSetTensorNdDescriptorEx": "NonBlocking",
    "cudnnSetTensorTransformDescriptor": "NonBlocking",
    "cudnnSetStream": "NonBlocking",
    "nvmlDeviceGetCount_v2": "NonBlocking",
    "nvmlInit_v2": "NonBlocking",
    "nvmlInitWithFlags": "NonBlocking",
}


def get_blocking_type(api_name: str) -> str:
    # if not find then error
    if api_name not in blocking_type_dict:
        # raise ValueError(f"Blocking type '{api_name}' not found in blocking_type_dict.")
        print(f"Blocking type '{api_name}' not found in blocking_type_dict.")
        return None
    return blocking_type_dict[api_name]

